/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-13 10:08:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modal_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>사이드바 예시</title>\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");


	



      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	.sidebar {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	.side2 {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 200px;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	.side3 {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 450px;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar li {\r\n");
      out.write("  margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul ul {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar li.active > ul {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".side2.act {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".side2 {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#folderList > li > a').click(function(event) {\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      $(this).parent().toggleClass('active');\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click','#product1',function(){\r\n");
      out.write("			\r\n");
      out.write("			$('#folderList2').parent().toggleClass('act');\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.member', function(){\r\n");
      out.write("			let sel = $(this).text();\r\n");
      out.write("			$('#select').val(sel);\r\n");
      out.write("			\r\n");
      out.write("			alert($('#select').val());\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#btn1', function(){\r\n");
      out.write("			let name = $('#select').val();\r\n");
      out.write("			let total = $('#app').text();\r\n");
      out.write("			\r\n");
      out.write("			total = total + name;\r\n");
      out.write("// 			$('#app').text(total);\r\n");
      out.write("			\r\n");
      out.write("			var nameLi = $(\"<li>\");\r\n");
      out.write("			nameLi.html(name);\r\n");
      out.write("			nameLi.addClass(\"selected\");\r\n");
      out.write("			\r\n");
      out.write("			$(\"#app1\").append(nameLi);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.selected', function(){\r\n");
      out.write("			let sel = $(this).text();\r\n");
      out.write("			$('#sltd').val(sel);\r\n");
      out.write("			\r\n");
      out.write("			alert($('#sltd').val());\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		$(document).on('click', '#btn1d', function(){	\r\n");
      out.write("			$('.selected').each(function() {\r\n");
      out.write("				if ($(this).text().trim() == $('#sltd').val()) {\r\n");
      out.write("				$(this).remove();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});c\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <ul id=\"folderList\">\r\n");
      out.write("      <li><a href=\"#\">인사부</a></li>\r\n");
      out.write("      <li><a href=\"#\">생산부</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a id=\"product1\">생산 1팀</a></li>\r\n");
      out.write("          <li><a href=\"#\">생산 2팀</a></li>\r\n");
      out.write("          <li><a href=\"#\">생산 3팀</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\">영업부</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("<div class=\"side2\">\r\n");
      out.write("    <ul id=\"folderList2\">\r\n");
      out.write("      <li><a href=\"#\">생산1팀</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a class=\"member\">박설희</a></li>\r\n");
      out.write("          <li><a class=\"member\">홍한솔</a></li>\r\n");
      out.write("          <li><a class=\"member\">이민호</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"side3\">\r\n");
      out.write("<table>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("		<input type=\"button\" id=\"btn1\" value=\"등록\"/><br>\r\n");
      out.write("		<input type=\"button\" id=\"btn1d\" value=\"삭제\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td class=\"box\" id=\"app\" style=\"background-color:red\">\r\n");
      out.write("		<ul id=\"app1\">\r\n");
      out.write("		</ul>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("		<input type=\"button\" id=\"btn2\" value=\"등록\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td class=\"box\" style=\"background-color:blue\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("		<input type=\"button\" id=\"btn3\" value=\"등록\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td class=\"box\" style=\"background-color:green\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"select\"/>\r\n");
      out.write("<input type=\"hidden\" id=\"sltd\"/>\r\n");
      out.write("  <script src=\"script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
