/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-14 07:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trDraftForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("			 <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("			 <link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  			 <script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("			 \r\n");
      out.write("			 .initial-size {\r\n");
      out.write("			  	min-height: 200px; \r\n");
      out.write("			  	width : 1000px;\r\n");
      out.write("			 }\r\n");
      out.write("			 \r\n");
      out.write("			\r\n");
      out.write("      		table {\r\n");
      out.write("	            border-collapse: collapse;\r\n");
      out.write("	            width: 1000px;\r\n");
      out.write("      		 }\r\n");
      out.write("      		 \r\n");
      out.write("        	th, td {\r\n");
      out.write("	            border: 1px solid black;\r\n");
      out.write("	            padding: 8px;\r\n");
      out.write("  		     }\r\n");
      out.write("\r\n");
      out.write("		</style>\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				$(document).on('click', '#dBtn', function() {\r\n");
      out.write("					alert(\"기안하기 >>>>> \");\r\n");
      out.write("					\r\n");
      out.write("					$('#draftForm').attr({\r\n");
      out.write("						'action':'',    \r\n");
      out.write("						'method':'POST',\r\n");
      out.write("						'enctype':'multipart/form-data'\r\n");
      out.write("					}).submit();\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("	<form name=\"draftForm\" id=\"draftForm\">\r\n");
      out.write("			\r\n");
      out.write("		<h2 align=\"center\">기안서</h2>\r\n");
      out.write("		<table border=\"1\" class=\"type\" name=\"type\" id=\"type\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"1\">\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\" height=\"40px;\">문서번호</th>\r\n");
      out.write("			<td><input type=\"hidden\" id=\"anum\" name=\"anum\" readonly></td>\r\n");
      out.write("			<th width=\"130px;\" height=\"40px;\">작성자</th>\r\n");
      out.write("			<td><input type=\"hidden\"  id=\"mnum\" name=\"mnum\" readonly></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\"  height=\"40px;\">보존연한</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			<select id=\"deletedate\" name=\"deletedate\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"deletedate1\" selected>보존연한</option>\r\n");
      out.write("				<option value=\"1\">1</option>\r\n");
      out.write("				<option value=\"2\">2</option>\r\n");
      out.write("				<option value=\"3\">3</option>\r\n");
      out.write("				<option value=\"4\">4</option>\r\n");
      out.write("				<option value=\"5\">5</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			년</td>\r\n");
      out.write("			<th width=\"130px;\"  height=\"40px;\">보안등급</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			<select id=\"aauth\" name=\"aauth\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"aauth1\" selected>보안등급</option>\r\n");
      out.write("				<option value=\"S\">S</option>\r\n");
      out.write("				<option value=\"A\">A</option>\r\n");
      out.write("				<option value=\"B\">B</option>\r\n");
      out.write("				<option value=\"C\">C</option>\r\n");
      out.write("				<option value=\"D\">D</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<button type=\"button\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "modal.jsp", out, false);
      out.write("</button><br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table border=\"1\" class=\"vac_sign\" name=\"vac_sign\" id=\"vac_sign\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"5\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th rowspan=\"3\" width=\"130px;\">신청</th>\r\n");
      out.write("			<td class=\"mposition\"></td>\r\n");
      out.write("			<td class=\"mposition\"></td>\r\n");
      out.write("			<td class=\"mposition\"></td>\r\n");
      out.write("			<td class=\"mposition\"></td>\r\n");
      out.write("			<td class=\"mposition\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"a\">\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"rank\">\r\n");
      out.write("			<td id=\"r1\"></td>\r\n");
      out.write("			<td id=\"r2\"></td>\r\n");
      out.write("			<td id=\"r3\"></td>\r\n");
      out.write("			<td id=\"r4\"></td>\r\n");
      out.write("			<td id=\"r5\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\">참조</th>\r\n");
      out.write("			<td colspan=\"6\" style=\"height:50px;\" name=\"areftext\" id=\"areftext\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<br>\r\n");
      out.write("	\r\n");
      out.write("		<br>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"130px\">제　　목</th>\r\n");
      out.write("				<td><input type=\"text\" name=\"dsubject\" id=\"dsubject\" size=\"112px\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <div id=\"editor\" class=\"initial-size\"></div>\r\n");
      out.write("    <input type=\"hidden\" id=\"quill_html\" name=\"dmemo\">\r\n");
      out.write("    <script>\r\n");
      out.write("		\r\n");
      out.write("  		var quill = new Quill('#editor', {\r\n");
      out.write("    	  // Quill 설정 옵션\r\n");
      out.write("    	});\r\n");
      out.write("\r\n");
      out.write("    	// 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("    	var editorContainer = document.querySelector('#editor');\r\n");
      out.write("    	editorContainer.addEventListener('click', function() {\r\n");
      out.write("    	  quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("    	});\r\n");
      out.write("    \r\n");
      out.write("        var toolbarOptions = [\r\n");
      out.write("            ['bold', 'italic', 'underline', 'strike'],\r\n");
      out.write("            ['link', 'image'],\r\n");
      out.write("            [{ 'list': 'ordered' }, { 'list': 'bullet' }],\r\n");
      out.write("            [{ 'header': [1, 2] }]\r\n");
      out.write("        ];\r\n");
      out.write("		\r\n");
      out.write("        var quill = new Quill('#editor', {\r\n");
      out.write("            modules: {\r\n");
      out.write("                toolbar: toolbarOptions\r\n");
      out.write("            },\r\n");
      out.write("            theme: 'snow'\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function myFunction(){\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input type=\"hidden\" name=\"dmemo\" id=\"dmemo\"/>\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px\">첨 부 파 일</th>\r\n");
      out.write("			<td>\r\n");
      out.write("  				<label for=\"file-upload\"></label>\r\n");
      out.write(" 			    <input type=\"file\" id=\"dfile\" name=\"dfile\">\r\n");
      out.write("	</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<button type=\"button\" id=\"dBtn\" name=\"dBtn\">기안하기</button>\r\n");
      out.write("		\r\n");
      out.write("	</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
