/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-26 06:37:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraMember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kos.tr.member.vo.TerraMemberVO;
import java.util.ArrayList;
import com.kos.tr.common.CodeUtil;

public final class memAddCard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kos.tr.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	Object obj = request.getAttribute("listAll");
	if (obj == null) return;
	
	ArrayList<TerraMemberVO> aList = (ArrayList<TerraMemberVO>)obj;


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	td{\r\n");
      out.write("		border-collapse:collapse;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    .modal {\r\n");
      out.write("      display: none; /* 초기에는 모달 창을 숨김 */\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      background-color: rgba(0, 0, 0, 0.5); /* 배경을 반투명하게 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      width: 650px;\r\n");
      out.write("      margin: 100px auto; /* 화면 중앙에 위치하도록 설정 */\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		$('.contents').click(function() {\r\n");
      out.write("		  // 모달 창 보이기\r\n");
      out.write("			\r\n");
      out.write("			$('#myModal').css('display', 'block');\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 모달 창 닫기 버튼 클릭 이벤트 처리\r\n");
      out.write("		$('#closeBtn').click(function() {\r\n");
      out.write("		  // 모달 창 닫기\r\n");
      out.write("		  $('#myModal').css('display', 'none');\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 모달 창 -->\r\n");
      out.write("<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("	<h4 id=\"emname\"></h4>\r\n");
      out.write("<table style=\"border-top:solid 1px;border-bottom:solid 1px;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td style=\"width:150px;height:30px;font-weight:bold;text-align:left\">&nbsp;&nbsp;이메일</td>\r\n");
      out.write("		<td id=\"email\" style=\"width:200px;height:30px;text-align:left\"></td>\r\n");
      out.write("		<td rowspan=\"5\" style=\"width:300px;height:250px\"><img id=\"photo\" style=\"width:250px;height:250px;padding:5px\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td style=\"width:150px;height:30px;font-weight:bold;text-align:left\">&nbsp;&nbsp;전화</td>\r\n");
      out.write("		<td id=\"hp\" style=\"width:200px;height:30px;text-align:left\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td style=\"width:150px;height:30px;font-weight:bold;text-align:left\">&nbsp;&nbsp;회사</td>\r\n");
      out.write("		<td style=\"width:200px;height:30px;text-align:left\">TERRA</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td style=\"width:150px;height:30px;font-weight:bold;text-align:left\">&nbsp;&nbsp;직위</td>\r\n");
      out.write("		<td id=\"position\" style=\"width:200px;height:30px;text-align:left\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td style=\"width:150px;height:30px;font-weight:bold;text-align:left\">&nbsp;&nbsp;부서</td>\r\n");
      out.write("		<td id=\"dept\" style=\"width:200px;height:30px;text-align:left\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<div style=\"text-align:center\">\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" id=\"closeBtn\">확인</button>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
