/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-07 14:42:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraMember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Terra Test Member Form</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("     	maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>     	\r\n");
      out.write("\r\n");
      out.write("<script  src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">     	\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/memInsert.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function previewImage(event) {\r\n");
      out.write("      var reader = new FileReader();\r\n");
      out.write("      reader.onload = function() {\r\n");
      out.write("        var output = document.getElementById('preview');\r\n");
      out.write("        output.src = reader.result;\r\n");
      out.write("      };\r\n");
      out.write("      reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  	\r\n");
      out.write("  	$(document).ready(function(){\r\n");
      out.write("  		var idChk = \"FAIL\";\r\n");
      out.write("  		var ar = false;\r\n");
      out.write("  		\r\n");
      out.write("  		// 아이디 중복체크 Ajax 비동기 방식  시작  ================================================= 				\r\n");
      out.write("		$(document).on(\"change\", \"#mid\", function(){\r\n");
      out.write("			var mid = $(\"#mid\").val();\r\n");
      out.write("			  if (mid === \"\") {\r\n");
      out.write("			    $(\"#idtext\").text('아이디를 입력해주세요');\r\n");
      out.write("			    $(\"#idtext\").css('display', 'block');\r\n");
      out.write("			    idChk = \"FAIL\";\r\n");
      out.write("			    return;\r\n");
      out.write("			  }\r\n");
      out.write("			  \r\n");
      out.write("			  // 아이디 유효성 검사 로직\r\n");
      out.write("			  var regex = /^[a-zA-Z0-9]+$/;\r\n");
      out.write("			  if (!regex.test(mid)) {\r\n");
      out.write("			    $(\"#idtext\").text('아이디는 영문자와 숫자로만 구성되어야 합니다');\r\n");
      out.write("			    $(\"#idtext\").css('display', 'block');\r\n");
      out.write("			    idChk = \"FAIL\";\r\n");
      out.write("			    return;\r\n");
      out.write("			  }\r\n");
      out.write("			  \r\n");
      out.write("			// 아이디 중복 체크 로직\r\n");
      out.write("			  var idCheckURL = \"tMemIdcheck.tr\";\r\n");
      out.write("			  var reqType = \"GET\";\r\n");
      out.write("			  var dataParam = { mid: mid };\r\n");
      out.write("			  \r\n");
      out.write("			  $.ajax({\r\n");
      out.write("			    url: idCheckURL,\r\n");
      out.write("			    type: reqType,\r\n");
      out.write("			    data: dataParam,\r\n");
      out.write("			    success: whenSuccess,\r\n");
      out.write("			    error: whenError\r\n");
      out.write("			  });\r\n");
      out.write("\r\n");
      out.write("			  function whenSuccess(resData) {\r\n");
      out.write("			    if (resData === \"ID_YES\") {\r\n");
      out.write("			      $(\"#idtext\").css('display', 'none');\r\n");
      out.write("			      idChk = \"PASS\";\r\n");
      out.write("		\r\n");
      out.write("			    } else if (resData === \"ID_NO\") {\r\n");
      out.write("			      $(\"#idtext\").text('사용할 수 없는 아이디입니다');\r\n");
      out.write("			      $(\"#idtext\").css('display', 'block');\r\n");
      out.write("			      idChk = \"FAIL\";\r\n");
      out.write("			    }\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  function whenError(e) {\r\n");
      out.write("			    console.log(\"Error: \" + e.responseText);\r\n");
      out.write("			  }\r\n");
      out.write("		});\r\n");
      out.write("  		\r\n");
      out.write("		$(\"#mpw\").keyup(function(){\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               async:false,\r\n");
      out.write("               url:\"pwCheck.tr\",\r\n");
      out.write("               type:\"GET\",\r\n");
      out.write("               data:{mpw : $(\"#mpw\").val()},\r\n");
      out.write("               success:pwCheck,\r\n");
      out.write("               error:pwChecke\r\n");
      out.write("               \r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            function pwCheck(data) {\r\n");
      out.write("               \r\n");
      out.write("               var array = data.split(\"+\");\r\n");
      out.write("                           \r\n");
      out.write("               var ar0 = array[0] == \"true\";\r\n");
      out.write("               var ar1 = array[1] == \"true\";\r\n");
      out.write("               var ar2 = array[2] == \"true\";\r\n");
      out.write("               var ar3 = array[3] == \"true\";\r\n");
      out.write("               \r\n");
      out.write("               if(ar0 && ar1 && ar2 && ar3) {\r\n");
      out.write("                  ar = true;\r\n");
      out.write("                  $(\"#pwtext\").css('display', 'none');\r\n");
      out.write("               }else{\r\n");
      out.write("            	  ar = false;\r\n");
      out.write("            	  $(\"#pwtext\").css('display', 'block');\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            function pwChecke(e) {\r\n");
      out.write("               alert(JSON.stringify(e));\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("		\r\n");
      out.write("         $(\"#mpw, #mpw_r\").keyup(function(){\r\n");
      out.write("            pw_nCnt = 0;\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("  	\r\n");
      out.write("		// 입사일\r\n");
      out.write("		$(\"#hiredate\").datepicker({		             \r\n");
      out.write("			dateFormat: \"yymmdd\",             \r\n");
      out.write("			changeMonth: true,                  			            \r\n");
      out.write("		});	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("        // 월 \r\n");
      out.write("        $(\"#miredate1\").append(\"<option value=''>월--- </option>\");\r\n");
      out.write("        for(var i = 1; i <= 12; i++){\r\n");
      out.write("        	if (i < 10){ i = '0'+i;}\r\n");
      out.write("            $(\"#miredate1\").append(\"<option value='\"+ i +\"'>\"+ i + \"</option>\");\r\n");
      out.write("        }\r\n");
      out.write("        // 일 \r\n");
      out.write("        $(\"#miredate2\").append(\"<option value=''>일 ---</option>\");\r\n");
      out.write("        for(var i = 1; i <= 31; i++){\r\n");
      out.write("        	if (i < 10){ i = '0'+i;}\r\n");
      out.write("            $(\"#miredate2\").append(\"<option value='\"+ i +\"'>\"+ i + \"</option>\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("     // 우편번호\r\n");
      out.write("		$(\"#mzipcode\").prop('readonly', true);\r\n");
      out.write("		$(\"#mroadaddr\").prop('readonly', true);\r\n");
      out.write("		$(\"#mjibun\").prop('readonly', true);		\r\n");
      out.write("		$(\"#zonecode\").click(function(){\r\n");
      out.write("			console.log(\"zonecode >>> : \");\r\n");
      out.write("			new daum.Postcode({\r\n");
      out.write("				oncomplete: function(data) {\r\n");
      out.write("				    $(\"#mzipcode\").val(data.zonecode); //5자리 새우편번호 사용\r\n");
      out.write("				    $(\"#mroadaddr\").val(data.roadAddress); //도로명 주소\r\n");
      out.write("				    $(\"#mjibun\").val(data.jibunAddress); //지번주소			\r\n");
      out.write("				}\r\n");
      out.write("			}).open();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 이메일 \r\n");
      out.write("		$('#memail2').change(function(){	\r\n");
      out.write("		$(\"#memail2 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#memail1\").val();					\r\n");
      out.write("					$(\"#memail1\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#memail1\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}}); \r\n");
      out.write("		}); \r\n");
      out.write("		\r\n");
      out.write("		// 폼태그 데이터 콘트롤러에 보내기 \r\n");
      out.write("		$(document).on(\"click\", \"#btn\", function(){	\r\n");
      out.write("			console.log(\"btn >>> : \");	\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			if (idChk == 'PASS' && ar) {\r\n");
      out.write("				\r\n");
      out.write("				$('#memForm').attr({\r\n");
      out.write("					'action':'tMemInsertForm.tr',\r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'multipart/form-data'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}else{\r\n");
      out.write("				alert('필수정보를 입력해주세요');\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("  	});\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("			function previewImage(event) {\r\n");
      out.write("				var reader = new FileReader();\r\n");
      out.write("				reader.onload = function () {\r\n");
      out.write("					var preview = document.getElementById('preview');\r\n");
      out.write("					preview.src = reader.result;\r\n");
      out.write("				}\r\n");
      out.write("				reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("	<form name=\"memForm\" id=\"memForm\">\r\n");
      out.write("		<h3><img src=\"../tr_spring/resources/images/logo-white.png\" onclick=\"javascript:location.href='/tr_spring/mainPage.tr'\" style=\"cursor:pointer\"></h3>\r\n");
      out.write("		<div class=\"all\">\r\n");
      out.write("			\r\n");
      out.write("			<table>\r\n");
      out.write("			\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"U\" colspan=\"3\" align=\"center\">					\r\n");
      out.write("						<span style=\"font-weight:bold;font-size:20px;color:#534825\">사원 등록 </span>					\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			\r\n");
      out.write("				 <tr>\r\n");
      out.write("				 	<td class=\"a\">아이디</td>\r\n");
      out.write("			        <td class=\"b\">\r\n");
      out.write("			            <input type=\"text\" name=\"mid\" id=\"mid\" placeholder=\"아이디\" required />\r\n");
      out.write("			            <p id=\"idtext\" style=\"display:none;color:red;font-size:12px;margin:0\">사용할 수 없는 아이디입니다</p>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td class=\"b\" rowspan=\"6\" style=\"text-align:center\">\r\n");
      out.write("			        <br>\r\n");
      out.write("						<img id=\"preview\" src=\"../tr_spring/resources/images/user.png\">\r\n");
      out.write("						<input type=\"file\" accept=\"image/*\" onchange=\"previewImage(event)\" name=\"mphoto\" id=\"mphoto\">\r\n");
      out.write("					</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td class=\"a\">비밀번호</td>\r\n");
      out.write("			        <td class=\"b\">\r\n");
      out.write("			            <input type=\"text\" class=\"imf\" name=\"mpw\" id=\"mpw\" placeholder=\"비밀번호\" maxlength=\"20\" required /><br>\r\n");
      out.write("			            <p id=\"pwtext\" style=\"display:none;color:red;font-size:12px;margin:0\">8~20자의 영문 대/소문자, 숫자, 특수문자를 사용해 주세요. </p>\r\n");
      out.write("			        </td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">생년월일</td>\r\n");
      out.write("					<td class=\"b\">\r\n");
      out.write("						<input type=\"text\" name=\"mbirth\" id=\"mbirth\" placeholder=\"생년월일 (8자리)\" maxlength=\"8\" style=\"width:100px\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">이름</td>\r\n");
      out.write("					<td class=\"b\">\r\n");
      out.write("						<input type=\"text\" name=\"mname\" id=\"mname\" placeholder=\"이름\" required /></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">성별</td>\r\n");
      out.write("					<td class=\"b\">\r\n");
      out.write("						<input type=\"radio\" name=\"mgender\" id=\"mgender_m\" style=\"background-color: #92D050\" value=\"M\" checked />남자 \r\n");
      out.write("						<input type=\"radio\" name=\"mgender\" id=\"mgender_f\" style=\"background-color: #92D050\" value=\"F\" />여자\r\n");
      out.write("				 	</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">이메일</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<input type=\"text\" name=\"memail\" id=memail style=\"width:100px\"  placeholder=\"이메일\"/>\r\n");
      out.write("						@ <input type=\"text\" name=\"memail1\" id=memail1 style=\"width:100px\" placeholder=\"직접입력\" />\r\n");
      out.write("						<select name=\"memail2\" id=\"memail2\" style=\"width:100px;margin-right:10px\">\r\n");
      out.write("								<option value=\"1\" selected>직접입력</option>\r\n");
      out.write("								<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("								<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("								<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("							</select>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">주소</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<input type=\"text\" name=\"mzipcode\" id=\"mzipcode\" placeholder=\"우편번호\" style=\"width:50px\">\r\n");
      out.write("						<input type=\"button\" name=\"zonecode\" id=\"zonecode\" value=\"우편번호 찾기\"><br>	 	\r\n");
      out.write("						<input type=\"text\" name=\"mroadaddr\" id=\"mroadaddr\" placeholder=\"도로명주소\" style=\"width:250px\"><br>	 	\r\n");
      out.write("						<input type=\"text\" name=\"mroaddetail\" id=\"mroaddetail\" placeholder=\"상세주소\" style=\"width:250px\"><br>	 	\r\n");
      out.write("						<input type=\"text\" name=\"mjibun\" id=\"mjibun\" placeholder=\"지번주소\" style=\"width:250px\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>	 \r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">핸드폰 번호</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<select name=\"mhp\" id=\"mhp\" >\r\n");
      out.write("							   <option value=\"010\" selected>010</option>\r\n");
      out.write("							   <option value=\"011\">011</option>\r\n");
      out.write("							   <option value=\"016\">016</option>\r\n");
      out.write("							   <option value=\"017\">017</option>		        	\r\n");
      out.write("						</select>\r\n");
      out.write("						- <input type=\"text\" name=\"mhp1\" id=\"mhp1\" maxlength=\"4\" size=\"2\" />\r\n");
      out.write("						- <input type=\"text\" name=\"mhp2\" id=\"mhp2\" maxlength=\"4\" size=\"2\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">입사일</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<input type=\"text\" name=\"hiredate\" id=\"hiredate\" size=\"10\" placeholder=\"입사일\" style=\"width:100px\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">부서</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<select name=\"mdeptno\" id=\"mdeptno\">\r\n");
      out.write("							   <option value=\"00\" selected>부서선택</option>\r\n");
      out.write("							   <option value=\"1000\">관리부</option>\r\n");
      out.write("							   <option value=\"2000\">기획부</option>\r\n");
      out.write("							   <option value=\"3000\">영업부</option>\r\n");
      out.write("							   <option value=\"4000\">생산부</option>\r\n");
      out.write("							   <option value=\"5000\">안전관리</option>		        	\r\n");
      out.write("						</select>\r\n");
      out.write("					   </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">직무</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<select name=\"mjob\" id=\"mjob\">\r\n");
      out.write("								   <option value=\"00\" selected>직무선택</option>\r\n");
      out.write("								   <option value=\"DEV\">개발</option>\r\n");
      out.write("								   <option value=\"BUS\">영업</option>\r\n");
      out.write("								   <option value=\"AFF\">총무</option>\r\n");
      out.write("								   <option value=\"PLAN\">기획</option>\r\n");
      out.write("								   <option value=\"PROD\">생산</option>	\r\n");
      out.write("						</select>\r\n");
      out.write("					 </td>\r\n");
      out.write("					 \r\n");
      out.write("				</tr>	\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">직위</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("					<select name=\"mposition\" id=\"mposition\">\r\n");
      out.write("							   <option value=\"00\" selected>직위선택</option>\r\n");
      out.write("							   <option value=\"01\">사원</option>\r\n");
      out.write("							   <option value=\"02\">대리</option>\r\n");
      out.write("							   <option value=\"03\">차장</option>\r\n");
      out.write("							   <option value=\"04\">과장</option>\r\n");
      out.write("							   <option value=\"05\">임원</option>	\r\n");
      out.write("							   <option value=\"06\">대표이사</option>	        	\r\n");
      out.write("						</select>\r\n");
      out.write("				</tr>	\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">상급자 번호</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<input type=\"text\" name=\"mgrno\" id=\"mgrno\" placeholder=\"상급자 번호\" style=\"width:150px\" >\r\n");
      out.write("				 	</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"a\">사내 번호</td>\r\n");
      out.write("					<td class=\"b\" colspan=\"2\">\r\n");
      out.write("						<input type=\"text\" name=\"mtel\" id=\"mtel\" maxlength=\"3\" size=\"2\"/>\r\n");
      out.write("						- <input type=\"text\" name=\"mtel1\" id=\"mtel1\" maxlength=\"4\" size=\"2\"/>\r\n");
      out.write("						- <select name=\"mtel2\" id=\"mtel2\">\r\n");
      out.write("							   <option value=\"00\" selected>사내번호</option>\r\n");
      out.write("							   <option value=\"5000\">5000</option>\r\n");
      out.write("							   <option value=\"5001\">5001</option>\r\n");
      out.write("							   <option value=\"5002\">5002</option>\r\n");
      out.write("							   <option value=\"5003\">5003</option>\r\n");
      out.write("							   <option value=\"5004\">5004</option>\r\n");
      out.write("							   <option value=\"5005\">5005</option>		        	\r\n");
      out.write("						</select>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"but\" colspan=\"3\" align=\"center\"> 			\r\n");
      out.write("						<button type=\"button\" id=\"btn\" class=\"btn btn-primary\" style=\"font-size:18px;background-color:#92D050;border-color:#92D050;width:100px;height:40px;color:white;align-items: center;\">SIGN IN</button>\r\n");
      out.write("					</td>				\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
