/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-31 09:37:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraMember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import com.kos.tr.member.vo.TerraMemberVO;
import java.util.List;

public final class memSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 request.setCharacterEncoding("UTF-8");
      out.write(' ');
      out.write('\r');
      out.write('\n');

	Logger logger = LogManager.getLogger(this.getClass());
	logger.info("memSelect.jsp >>> : ");

      out.write("\r\n");
      out.write("\r\n");
	
	Object obj = request.getAttribute("listS");
	if (obj == null) return;

	List<TerraMemberVO> list = (List<TerraMemberVO>)obj;	
	int nCnt = list.size();
	
	String mpw = "";
	String mbirth = "";
	String mbirth0 = "";
	String mbirth1 = "";
	String mbirth2 = "";
	String memail = "";	
	String memails[] = null;
	String mdeptno = ""; // 부서번호
	String mgrno = ""; // 상급자 번호
	String mduty = ""; // 직책
	String mposition = ""; // 직위
	String mjob = ""; // 직무
	
	TerraMemberVO _tmvo = null;	
	_tmvo = list.get(0);
	
	
	// 이메일
	memail = _tmvo.getMemail();
	memails = memail.split("@");
	
	
	// 상급자 번호
	mgrno = _tmvo.getMgrno();
	
	// 데이터베이스에서 가져온 핸드폰 번호 데이터
	String phoneNumber = _tmvo.getMhp();  // 데이터베이스에서 값을 가져오는 로직을 구현해야 합니다.

	// 핸드폰 번호를 분리하여 각 부분에 할당
	String mhp = phoneNumber.substring(0, 3);
	String mhp1 = phoneNumber.substring(3, 7);
	String mhp2 = phoneNumber.substring(7);
	
	// 데이터베이스에서 가져온 핸드폰 번호 데이터
	String mtelNumber = _tmvo.getMtel();  // 데이터베이스에서 값을 가져오는 로직을 구현해야 합니다.

	// 핸드폰 번호를 분리하여 각 부분에 할당
	String mtel = mtelNumber.substring(0, 3);
	String mtel1 = mtelNumber.substring(3, 7);
	String mtel2 = mtelNumber.substring(7);
		

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>select page</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("     	maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>     	\r\n");
      out.write("\r\n");
      out.write("<script  src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">     	\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/memSelect.css\">\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	function previewImage(event) {\r\n");
      out.write("	    var reader = new FileReader();\r\n");
      out.write("	    reader.onload = function() {\r\n");
      out.write("	        var output = document.getElementById('preview');\r\n");
      out.write("	        output.src = reader.result;\r\n");
      out.write("	        output.style.display = \"block\"; // 미리보기 이미지를 화면에 보이도록 설정합니다\r\n");
      out.write("	    };\r\n");
      out.write("	    reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#mdeptno1').val(\"");
      out.print(_tmvo.getMdeptno());
      out.write("\");\r\n");
      out.write("	$('#mjob').val(\"");
      out.print(_tmvo.getMjob());
      out.write("\");\r\n");
      out.write("	$('#mposition').val(\"");
      out.print(_tmvo.getMposition());
      out.write("\");mtel2\r\n");
      out.write("	$('#mtel2').val(\"");
      out.print(mtel2);
      out.write("\");\r\n");
      out.write("	// 이메일 \r\n");
      out.write("	$('#memail2').change(function(){	\r\n");
      out.write("		$(\"#memail2 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#memail1\").val();						\r\n");
      out.write("					$(\"#memail1\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#memail1\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}\r\n");
      out.write("		}); \r\n");
      out.write("	}); 	\r\n");
      out.write("	\r\n");
      out.write("	// 우편번호	\r\n");
      out.write("	$(\"#zonecode\").click(function(){\r\n");
      out.write("		console.log(\"zonecode >>> : \");\r\n");
      out.write("		new daum.Postcode({\r\n");
      out.write("			oncomplete: function(data) {\r\n");
      out.write("			    $(\"#mzipcode\").val(data.mzipcode); 		//5자리 새우편번호 사용\r\n");
      out.write("			    $(\"#mroadaddr\").val(data.roadAddress); 		//도로명 주소\r\n");
      out.write("			    $(\"#mroaddetail\").val(''); 					// 도로명 상세주소\r\n");
      out.write("			    $(\"#mjibun\").val(data.mjibun); 	//지번주소			\r\n");
      out.write("			}\r\n");
      out.write("		}).open();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 부서 번호\r\n");
      out.write("	$('#mdeptno1').change(function(){	\r\n");
      out.write("		$(\"#mdeptno1 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#mdeptno\").val();						\r\n");
      out.write("					$(\"#mdeptno\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#mdeptno\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#mdeptno\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#mdeptno\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}\r\n");
      out.write("		}); \r\n");
      out.write("	}); 	\r\n");
      out.write("	\r\n");
      out.write("	// 직위 번호\r\n");
      out.write("	$('#mposition1').change(function(){	\r\n");
      out.write("		$(\"#mposition1 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#mposition\").val();						\r\n");
      out.write("					$(\"#mposition\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#mposition\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#mposition\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#mposition\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}\r\n");
      out.write("		}); \r\n");
      out.write("	}); \r\n");
      out.write("	\r\n");
      out.write("	// 직책 번호 mduty1\r\n");
      out.write("	$('#mduty1').change(function(){	\r\n");
      out.write("		$(\"#mduty1 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#mduty\").val();						\r\n");
      out.write("					$(\"#mduty\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#mduty\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#mduty\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#mduty\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}\r\n");
      out.write("		}); \r\n");
      out.write("	}); 	\r\n");
      out.write("	\r\n");
      out.write("	// 직책 번호 mjob1\r\n");
      out.write("	$('#mjob1').change(function(){	\r\n");
      out.write("		$(\"#mjob1 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#mjob\").val();						\r\n");
      out.write("					$(\"#mjob\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#mjob\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#mjob\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#mjob\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}\r\n");
      out.write("		}); \r\n");
      out.write("	}); \r\n");
      out.write("	\r\n");
      out.write("	// 전결권 번호 mpassyn1 \r\n");
      out.write("	$('input[name=\"mpassyn1\"]').change(function(){\r\n");
      out.write("	  var selectedValue = $('input[name=\"mpassyn1\"]:checked').val();\r\n");
      out.write("	  if (selectedValue === '1') { // 직접입력일 경우\r\n");
      out.write("	    $(\"#mpassyn\").val(''); // 값 초기화\r\n");
      out.write("	    $(\"#mpassyn\").prop(\"readonly\", false); // 활성화\r\n");
      out.write("	  } else { // 직접입력이 아닐 경우\r\n");
      out.write("	    $(\"#mpassyn\").val(selectedValue); // 선택값 입력\r\n");
      out.write("	    $(\"#mpassyn\").prop(\"readonly\", true); // 비활성화\r\n");
      out.write("	  }\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("	// 입사일\r\n");
      out.write("	$(\"#hiredate\").datepicker({		             \r\n");
      out.write("		dateFormat: \"yymmdd\",             \r\n");
      out.write("		changeMonth: true,                  			            \r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//updateBtn\r\n");
      out.write("$(document).on(\"click\", \"#updateBtn\", function(){\r\n");
      out.write("	//alert(\"U >>> : \");		\r\n");
      out.write("	$(\"#memUpdateForm\").attr({ \"method\":\"POST\"\r\n");
      out.write("		                      ,\"action\":\"tMemUpdate.tr\"\r\n");
      out.write("		                      ,'enctype':'multipart/form-data'\r\n");
      out.write("		                      }).submit();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<form name=\"memUpdateForm\" id=\"memUpdateForm\">	\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td class=\"U\" colspan=\"3\" align=\"center\">					\r\n");
      out.write("			<span style=\"font-weight:bold;font-size:20px;color:#534825\">사원 정보 수정 </span>						\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td class=\"title\">회원번호</td>\r\n");
      out.write("			<td class=\"input\">\r\n");
      out.write("				<input type=\"text\" name=\"mnum\" id=\"mnum\" value=\"");
      out.print( _tmvo.getMnum() );
      out.write("\" style=\"border:0\" readonly/>\r\n");
      out.write("			</td>\r\n");
      out.write("			\r\n");
      out.write("			<td class=\"input\" rowspan=\"5\">\r\n");
      out.write("			    <!-- 이미지를 조건에 따라 숨기거나 보여주기 -->\r\n");
      out.write("			    ");
 if (_tmvo.getMphoto() != null && !_tmvo.getMphoto().isEmpty()) { 
      out.write("\r\n");
      out.write("			        <img id=\"preview\" class=\"photo\" src=\"./fileupload/tmem/");
      out.print( _tmvo.getMphoto() );
      out.write("\" ><!-- 파일업로드전 -->\r\n");
      out.write("			    ");
 } 
      out.write("\r\n");
      out.write("			    <!-- 파일업로드후 \r\n");
      out.write("			    <img id=\"preview\" class=\"photo\" src=\"\" style=\"");
 if (_tmvo.getMphoto() != null && !_tmvo.getMphoto().isEmpty()) { 
      out.write(" display:none;");
 } 
      out.write("\">\r\n");
      out.write("			    -->\r\n");
      out.write("			    <!-- 파일 선택 입력 요소 -->\r\n");
      out.write("			    <input type=\"file\" accept=\"image/*\" onchange=\"previewImage(event)\" name=\"mphoto\" id=\"mphoto\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td class=\"title\">이름</td>\r\n");
      out.write("			<td class=\"input\">\r\n");
      out.write("				<input type=\"text\" name=\"mname\" id=\"mname\" value=\"");
      out.print( _tmvo.getMname() );
      out.write("\" style=\"border:0\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">아이디</td>\r\n");
      out.write("			<td class=\"input\">\r\n");
      out.write("				<input type=\"text\" name=\"mid\" id=\"mid\" style=\"width:100px;border:0\" value=\"");
      out.print( _tmvo.getMid() );
      out.write("\" readonly />		\r\n");
      out.write("			</td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">패스워드</td>\r\n");
      out.write("			<td class=\"input\">\r\n");
      out.write("				<input type=\"text\" name=\"mpw\" id=\"mpw\" style=\"width:100px\" value=\"");
      out.print( _tmvo.getMpw() );
      out.write("\" /><br/>\r\n");
      out.write("			</td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">성별</td>\r\n");
      out.write("			<td class=\"input\">\r\n");
      out.write("		      	<input type=\"text\" name=\"mgender\" id=\"mgender_m\" value=\"");
      out.print( _tmvo.getMgender() );
      out.write("\" style=\"border:0\" readonly />\r\n");
      out.write("		    </td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">생년월일</td>\r\n");
      out.write("			<td class=\"input\" colspan=\"2\">		\r\n");
      out.write("				<input type=\"text\" name=\"mbirth\" id=mbirth value=\"");
      out.print( _tmvo.getMbirth() );
      out.write("\" style=\"width:100px;border:0\" readonly/>\r\n");
      out.write("			</td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">핸드폰</td>\r\n");
      out.write("			<td class=\"input\" colspan=\"2\">\r\n");
      out.write("				<select name=\"mhp\" id=\"mhp\" style=\"width:50px;\" value=\"");
      out.print( mhp );
      out.write("\">\r\n");
      out.write("					<option value=\"010\" ");
      out.print( mhp.equals("010") ? "selected" : "" );
      out.write(">010</option>\r\n");
      out.write("					<option value=\"011\" ");
      out.print( mhp.equals("011") ? "selected" : "" );
      out.write(">011</option>\r\n");
      out.write("					<option value=\"016\" ");
      out.print( mhp.equals("016") ? "selected" : "" );
      out.write(">016</option>\r\n");
      out.write("					<option value=\"017\" ");
      out.print( mhp.equals("017") ? "selected" : "" );
      out.write(">017</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				- <input type=\"text\" name=\"mhp1\" id=\"mhp1\" value=\"");
      out.print( mhp1 );
      out.write("\" maxlength=\"4\" style=\"width:50px;\" />\r\n");
      out.write("				- <input type=\"text\" name=\"mhp2\" id=\"mhp2\" value=\"");
      out.print( mhp2 );
      out.write("\" maxlength=\"4\" style=\"width:50px;\" />\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("				 \r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">이메일</td>\r\n");
      out.write("			<td class=\"input\" colspan=\"2\">\r\n");
      out.write("				<input type=\"text\" name=\"memail\" id=memail style=\"width:100px\" value=\"");
      out.print( memails[0] );
      out.write("\" />\r\n");
      out.write("				@ <input type=\"text\" name=\"memail1\" id=memail1 style=\"width:100px\" value=\"");
      out.print( memails[1] );
      out.write("\" placeholder=\"직접입력\" />\r\n");
      out.write("				<select name=\"memail2\" id=\"memail2\" style=\"width:100px;margin-right:10px\">\r\n");
      out.write("		        	 <option value=\"1\" selected>직접입력</option>\r\n");
      out.write("		       		 <option value=\"naver.com\">naver.com</option>	       	   \r\n");
      out.write("		      		 <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("		      		 <option value=\"daum.net\">daum.net</option>	       	   \r\n");
      out.write("		         </select>\r\n");
      out.write("			</td>\r\n");
      out.write("		 </tr>\r\n");
      out.write("		 \r\n");
      out.write("		 <tr>	\r\n");
      out.write("		 	<td class=\"title\">주소</td>\r\n");
      out.write("		 	<td class=\"input\" colspan=\"2\">\r\n");
      out.write("		 		<input type=\"text\" name=\"mzipcode\" id=\"mzipcode\" \r\n");
      out.write("		 			style=\"width:50px\" value=\"");
      out.print( _tmvo.getMzipcode() );
      out.write("\">\r\n");
      out.write("		 		<input name=\"zonecode\" id=\"zonecode\" value=\"우편번호 찾기\"><br>	 	\r\n");
      out.write("		 		<input type=\"text\" name=\"mroadaddr\" id=\"mroadaddr\" \r\n");
      out.write("		 			placeholder=\"도로명주소\" style=\"width:300px\" value=\"");
      out.print( _tmvo.getMroadaddr() );
      out.write("\"><br>	 	\r\n");
      out.write("		 		<input type=\"text\" name=\"mroaddetail\" id=\"mroaddetail\" \r\n");
      out.write("		 			placeholder=\"도로명주소 상세주소\" style=\"width:300px\" value=\"");
      out.print( _tmvo.getMroaddetail() );
      out.write("\"><br>	 	\r\n");
      out.write("		 		<input type=\"text\" name=\"mjibun\" id=\"mjibun\" \r\n");
      out.write("		 			placeholder=\"지번주소\" style=\"width:300px\" value=\"");
      out.print( _tmvo.getMjibun() );
      out.write("\">\r\n");
      out.write("		 	</td>\r\n");
      out.write("		 </tr>	 \r\n");
      out.write("		 \r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	<td class=\"title\">상급자 번호</td>\r\n");
      out.write("			<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<input type=\"text\" name=\"mgrno\" id=\"mgrno\"  value=\"");
      out.print( _tmvo.getMgrno() );
      out.write("\" style=\"width:100px\">\r\n");
      out.write("					\r\n");
      out.write("			 	</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("			<tr>	 \r\n");
      out.write("				<td class=\"title\">부서 번호</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<select name=\"mdeptno\" id=\"mdeptno\">\r\n");
      out.write("						   <option value=\"1000\">관리부</option>\r\n");
      out.write("						   <option value=\"2000\">기획부</option>\r\n");
      out.write("						   <option value=\"3000\">영업부</option>\r\n");
      out.write("						   <option value=\"4000\">생산부</option>\r\n");
      out.write("						   <option value=\"5000\">안전관리</option>	        	\r\n");
      out.write("					</select>\r\n");
      out.write("				   </td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			<tr>	 \r\n");
      out.write("				<td class=\"title\">직무</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<select  name=\"mjob\" id=\"mjob\">\r\n");
      out.write("							   <option value=\"DEV\">개발</option>\r\n");
      out.write("							   <option value=\"BUS\">영업</option>\r\n");
      out.write("							   <option value=\"AFF\">총무</option>\r\n");
      out.write("							   <option value=\"PLAN\">기획</option>\r\n");
      out.write("							   <option value=\"PROD\">생산</option>	\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>	\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("			<tr>	 \r\n");
      out.write("				<td class=\"title\">직위</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<select name=\"mposition\" id=\"mposition\" >\r\n");
      out.write("						   <option value=\"01\">사원</option>\r\n");
      out.write("						   <option value=\"02\">대리</option>\r\n");
      out.write("						   <option value=\"03\">과장</option>\r\n");
      out.write("						   <option value=\"04\">부장</option>\r\n");
      out.write("						   <option value=\"05\">임원</option>	\r\n");
      out.write("						   <option value=\"06\">대표이사</option>        	\r\n");
      out.write("					</select>\r\n");
      out.write("			</tr>	\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			<tr>	 \r\n");
      out.write("				<td class=\"title\">전결권</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<input type=\"text\" name=\"mpassyn\" id=\"mpassyn\" value=\"");
      out.print( _tmvo.getMpassyn() );
      out.write("\" style=\"width:100px\">\r\n");
      out.write("					\r\n");
      out.write("						<input type=\"radio\" name=\"mpassyn1\" id=\"mpassyn1\" style=\"background-color: #92D050\" value=\"N\" checked />미부여 \r\n");
      out.write("						<input type=\"radio\" name=\"mpassyn1\" id=\"mpassyn1\" style=\"background-color: #92D050\" value=\"Y\" />부여      	\r\n");
      out.write("					\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>	\r\n");
      out.write("				\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"title\">입사일</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<input type=\"text\" name=\"hiredate\" id=\"hiredate\" size=\"10\" style=\"width:100px\" value=\"");
      out.print( _tmvo.getHiredate() );
      out.write("\" />\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"title\">연차</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<input type=\"text\" name=\"mholiday\" id=\"mholiday\" size=\"10\" style=\"width:100px\"  value=\"");
      out.print( _tmvo.getMholiday() );
      out.write("\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"title\">사내번호</td>\r\n");
      out.write("				<td class=\"input\" colspan=\"2\">\r\n");
      out.write("					<input type=\"text\" name=\"mtel\" id=\"mtel\" maxlength=\"3\" size=\"2\" value=\"");
      out.print( mtel );
      out.write("\"/>\r\n");
      out.write("					- <input  type=\"text\" name=\"mtel1\" id=\"mtel1\" maxlength=\"4\" size=\"2\" value=\"");
      out.print( mtel1 );
      out.write("\"/>\r\n");
      out.write("					- <select name=\"mtel2\" id=\"mtel2\"  >\r\n");
      out.write("						   <option value=\"5000\">5000</option>\r\n");
      out.write("						   <option value=\"5001\">5001</option>\r\n");
      out.write("						   <option value=\"5002\">5002</option>\r\n");
      out.write("						   <option value=\"5003\">5003</option>\r\n");
      out.write("						   <option value=\"5004\">5004</option>\r\n");
      out.write("						   <option value=\"5005\">5005</option>		        	\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr> \r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write(" <tr>\r\n");
      out.write("	<td colspan=\"3\" class=\"but\">\r\n");
      out.write("		<button type=\"button\" id=\"updateBtn\" class=\"btn btn-primary\" style=\"font-size:18px;background-color:#92D050;border-color:#92D050;width:100px;height:40px;color:white;align-items: center;\">수정</button>\r\n");
      out.write("		<button type=\"reset\" class=\"btn btn-primary\" style=\"font-size:18px;background-color:#92D050;border-color:#92D050;width:100px;height:40px;color:white;align-items: center;\">다시</button>\r\n");
      out.write("	</td>				\r\n");
      out.write(" </tr>\r\n");
      out.write(" </table>				 		        		     \r\n");
      out.write("</form>	\r\n");
      out.write("</div>		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
