/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-03 08:15:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraWork;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import java.util.List;
import java.util.ArrayList;
import com.kos.tr.work.vo.TerraWorkVO;
import com.kos.tr.member.vo.TerraMemberVO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class trWorkForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.slf4j.Logger");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("org.slf4j.LoggerFactory");
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("com.kos.tr.work.vo.TerraWorkVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 	request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 	Logger logger = LoggerFactory.getLogger(this.getClass()); 
      out.write('\r');
      out.write('\n');
 	logger.info("trWorkForm 진입"); 
      out.write('\r');
      out.write('\n');
 	ArrayList<TerraMemberVO> uList = (ArrayList<TerraMemberVO>)request.getAttribute("uList");
	TerraMemberVO mvo = uList.get(0);
	
	String mnum = uList.get(0).getMnum();
	logger.info("trWorkForm | 로그인세션 <<< mnum", mnum);
	
	// 
	Object wnchk = (String) request.getAttribute("datashift");
	
	String[] worknow_2 = null;
	String[] s_work = null;
	String wtime = null;
	String wstateL = null;
	int wlen = 0;
	

      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Personnel Management Page</title>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/tr_spring/resources/script/common.js\"></script>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maxinum-scale=1, user-scalable=no\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/tr_spring/resources/css/sidebars.css\">\r\n");
      out.write("	<link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/sidebars/\">\r\n");
      out.write("	<script src=\"/tr_spring/resources/js/util.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("	.icon_img{\r\n");
      out.write("		width:22px;\r\n");
      out.write("		height: 22px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		margin-left: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dropdown-toggle-no-caret::after {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.docimg{\r\n");
      out.write("		height:300px;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.doctext{\r\n");
      out.write("		font-weight:bold;\r\n");
      out.write("		font-size:25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#nowSelected{\r\n");
      out.write("		background-color: #C5E0B4;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("			$(document).on('mouseenter', '.idx', function(){\r\n");
      out.write("				\r\n");
      out.write("				$(this).css('background-color', '#ecf9ec');\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("			$(document).on('mouseleave', '.idx', function(){\r\n");
      out.write("		\r\n");
      out.write("				$(this).css('background-color', '#E2F0D9');\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("			$(document).on('mouseleave', '#nowSelected', function(){\r\n");
      out.write("		\r\n");
      out.write("				$(this).css('background-color', '#C5E0B4');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"GET\",\r\n");
      out.write("				url: '/tr_spring/appAlert.tr',\r\n");
      out.write("				success : function(result){\r\n");
      out.write("					\r\n");
      out.write("					if (result == 'ALERT_YES') {\r\n");
      out.write("						$('#bell').attr(\"src\", \"/tr_spring/resources/images/alert.png\")\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error: function(xtr, status, error){\r\n");
      out.write("					alert(xtr + \":\" + status + \":\" + error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 받아온 데이터를  한 번 더 처리\r\n");
      out.write("			var mnum = '");
      out.print(mnum);
      out.write("';\r\n");
      out.write("			$(\"#mnum\").val(mnum);\r\n");
      out.write("						\r\n");
      out.write("			var mnum_chk = $(\"#mnum\").val();\r\n");
      out.write("			console.log(\"mnum 값 : \" + mnum_chk +\" | \" + typeof(mnum_chk));\r\n");
      out.write("			\r\n");
      out.write("			// mnum의 null 체크\r\n");
      out.write("			$(function (){\r\n");
      out.write("				if(mnum_chk == \"null\"){\r\n");
      out.write("					alert(\"로그인세션없음\");\r\n");
      out.write("					callToMain();\r\n");
      out.write("				}else{\r\n");
      out.write("					restVacation();\r\n");
      out.write("					workHour();\r\n");
      out.write("					worknow();\r\n");
      out.write("					workEtc();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 근무상태 변경 버튼 jQuery 시작 ================================\r\n");
      out.write("			var wchange = null;	\r\n");
      out.write("				\r\n");
      out.write("			// 업무:01\r\n");
      out.write("			$(\"#sWork\").click(function(){\r\n");
      out.write("				wchange = $(\"#sWork\").val();\r\n");
      out.write("				callWchange();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 외근:02\r\n");
      out.write("			$(\"#sWo\").click(function(){\r\n");
      out.write("				wchange = $(\"#sWo\").val();\r\n");
      out.write("				callWchange();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 외출:03\r\n");
      out.write("			$(\"#sOut\").click(function(){\r\n");
      out.write("				wchange = $(\"#sOut\").val();\r\n");
      out.write("				callWchange();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 회의:04\r\n");
      out.write("			$(\"#sCon\").click(function(){\r\n");
      out.write("				wchange = $(\"#sCon\").val();\r\n");
      out.write("				callWchange();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 퇴근하기:05\r\n");
      out.write("			$(\"#sLto\").click(function(){\r\n");
      out.write("				wchange = $(\"#sLto\").val();\r\n");
      out.write("				callWchange();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 조퇴:05\r\n");
      out.write("			$(\"#sElto\").click(function(){\r\n");
      out.write("				\r\n");
      out.write("				let today = new Date();   \r\n");
      out.write("				let hours = ('0' + today.getHours()).slice(-2); \r\n");
      out.write("				let minutes = ('0' + today.getMinutes()).slice(-2);\r\n");
      out.write("\r\n");
      out.write("				let timeString = hours + minutes;\r\n");
      out.write("				console.log(timeString);\r\n");
      out.write("				let timeInt = parseInt(timeString);\r\n");
      out.write("				console.log(\"timeInt | \" + timeInt + \" | type | \" + typeof(timeInt));\r\n");
      out.write("				let timechk = 1800;\r\n");
      out.write("				console.log(\"timechk | \" + timechk + \" | type | \" + typeof(timechk));\r\n");
      out.write("				\r\n");
      out.write("				if (timeInt < timechk){\r\n");
      out.write("					wchange = $(\"#sElto\").val();\r\n");
      out.write("					callWchange();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			// 근무상태 변경 버튼 jQuery 종료 ================================\r\n");
      out.write("			\r\n");
      out.write("			// 근태현황 | 지각, 조퇴, 퇴근미체크, 결근\r\n");
      out.write("			function workEtc(){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workEtc.tr\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					data: {	mnum: $(\"#mnum\").val()},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError\r\n");
      out.write("				}); // end of ajax : 근태현황\r\n");
      out.write("				\r\n");
      out.write("				//etcData \r\n");
      out.write("				function whenSuccess(etcData) {	\r\n");
      out.write("					console.log(\"근태현황 리턴성공 >>> : \" + etcData);\r\n");
      out.write("					console.log(\"근태현황 리턴 타입 : \" + typeof(etcData));\r\n");
      out.write("					let wEtc = etcData.split(\",\");\r\n");
      out.write("					console.log(\"근태현황 자르기 1번째 | 지각 \" + wEtc[0]);\r\n");
      out.write("					console.log(\"근태현황 자르기 2번째 | 조퇴 \" + wEtc[1]);\r\n");
      out.write("					console.log(\"근태현황 자르기 3번째 | 퇴근미체크 \" + wEtc[2]);\r\n");
      out.write("					console.log(\"근태현황 자르기 마지막 | 결근 \" + wEtc[3]);\r\n");
      out.write("					$('#late').text(wEtc[0]);\r\n");
      out.write("					$('#early').text(wEtc[1]);\r\n");
      out.write("					$('#notchk').text(wEtc[2]);\r\n");
      out.write("					$('#absence').text(wEtc[3]);\r\n");
      out.write("					\r\n");
      out.write("				}					\r\n");
      out.write("			\r\n");
      out.write("				function whenError(e){\r\n");
      out.write("					alert(\"근태현황 통신실패 >>>> : \");\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("				\r\n");
      out.write("			// 잔여휴가>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\r\n");
      out.write("			function restVacation() {\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workSelectVa.tr\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					data: {	mnum: $(\"#mnum\").val()},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError\r\n");
      out.write("				}); // end of ajax : 잔여휴가\r\n");
      out.write("				\r\n");
      out.write("				function whenSuccess(vaData) {	\r\n");
      out.write("					console.log(\"휴가 리턴 데이터 출력 >>> : \" + vaData);\r\n");
      out.write("					$(\"#restvacation\").val(vaData);\r\n");
      out.write("				}					\r\n");
      out.write("				\r\n");
      out.write("				function whenError(e){\r\n");
      out.write("					alert(JSON.stringify(e));\r\n");
      out.write("				}\r\n");
      out.write("				//잔여휴가 끝<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// INSERT : 출근하기 버튼 AJAX\r\n");
      out.write("			$('#sCtw').click(function(){\r\n");
      out.write("				callAjax();\r\n");
      out.write("				callPython();\r\n");
      out.write("				\r\n");
      out.write("			}); // end of $('#ctW').click\r\n");
      out.write("			\r\n");
      out.write("			function callAjax(){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workInsert.tr\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					data: {	\r\n");
      out.write("							mnum: $(\"#mnum\").val(),\r\n");
      out.write("							wstate: $(\"#sCtw\").val()\r\n");
      out.write("							},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError,\r\n");
      out.write("				}); // end of ajax\r\n");
      out.write("\r\n");
      out.write("				function whenSuccess(resData) {\r\n");
      out.write("					worknow();\r\n");
      out.write("				} // 출근하기 성공시, select 함수 호출\r\n");
      out.write("				function whenError(){\r\n");
      out.write("					\r\n");
      out.write("					alert(\"callAjax() | error\");\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			} //INSEERT : 출근하기 END \r\n");
      out.write("			\r\n");
      out.write("			function callPython(){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"http://192.168.0.36:5000/chulgeun\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError,\r\n");
      out.write("				}); // end of ajax\r\n");
      out.write("\r\n");
      out.write("				function whenSuccess(resData) {\r\n");
      out.write("				}\r\n");
      out.write("				function whenError(){\r\n");
      out.write("				}\r\n");
      out.write("			} //INSEERT : 출근하기 END \r\n");
      out.write("			// 현재시각 표시===================================================\r\n");
      out.write("			$(function Time(){\r\n");
      out.write("			// 현재 시간 표시 시작\r\n");
      out.write("				function printTime(){\r\n");
      out.write("					let md = new Date();\r\n");
      out.write("					\r\n");
      out.write("					let hh = ('0' + md.getHours()).slice(-2);\r\n");
      out.write("					let mi = ('0' + md.getMinutes()).slice(-2);\r\n");
      out.write("					let ss = ('0' + md.getSeconds()).slice(-2);\r\n");
      out.write("					\r\n");
      out.write("					let time = 	numpad(hh) + \":\" +\r\n");
      out.write("								numpad(mi) + \":\" +\r\n");
      out.write("								numpad(ss);\r\n");
      out.write("					document.getElementById(\"timer\").innerHTML=time;\r\n");
      out.write("				}\r\n");
      out.write("				setInterval(printTime, 1000);\r\n");
      out.write("\r\n");
      out.write("			}); // 현재시간 표시 끝\r\n");
      out.write("			// 현재시각 표시 END===============================================\r\n");
      out.write("			\r\n");
      out.write("			// mnum값 없으면(세션 없음) 로그인 메인으로 이동\r\n");
      out.write("			function callToMain() {\r\n");
      out.write("				\r\n");
      out.write("				$('#trForm').attr({\r\n");
      out.write("					'action':'loginForm.tr',\r\n");
      out.write("					'method':'GET',\r\n");
      out.write("					'enctype':'multipart/form-data'\r\n");
      out.write("				}).submit();				\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 출근 외 상태 변화\r\n");
      out.write("			function callWchange(){\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workUpdate.tr\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					data: {	\r\n");
      out.write("							mnum: $(\"#mnum\").val(),\r\n");
      out.write("							wstate: wchange,\r\n");
      out.write("							startdate:$(\"#startdate\").val(),\r\n");
      out.write("							enddate: $(\"#enddate\").val()							\r\n");
      out.write("						},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError,\r\n");
      out.write("				}); // end of ajax : 근무상태변화\r\n");
      out.write("				\r\n");
      out.write("				function whenSuccess(cwData) {	\r\n");
      out.write("					console.log(\"근무상태변화 리턴  성공>>> : \" );\r\n");
      out.write("					worknow();\r\n");
      out.write("				}					\r\n");
      out.write("				\r\n");
      out.write("				function whenError(e){\r\n");
      out.write("					alert(\"출근 외 상태변화 >>> : \" + JSON.stringify(e));\r\n");
      out.write("				}\r\n");
      out.write("			} // end of callWchange()\r\n");
      out.write("			\r\n");
      out.write("			// 올해 근무 정보 - 근무시간>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\r\n");
      out.write("			function workHour(){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workHour.tr\",\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					data: {	mnum: $(\"#mnum\").val()},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError\r\n");
      out.write("				}); // end of ajax : 잔여휴가\r\n");
      out.write("				\r\n");
      out.write("				//whData : dayNhour\r\n");
      out.write("				function whenSuccess(whData) {	\r\n");
      out.write("					console.log(\"올해 근무시간 정보 출력 >>> : \" + whData);\r\n");
      out.write("					let typechk = typeof(whData);\r\n");
      out.write("					console.log(\"올해 근무시간 데이터타입 >>> \" + typechk);\r\n");
      out.write("					let arrwhData = whData.split(\",\");\r\n");
      out.write("					$(\"#workday\").text(arrwhData[0]);  // 근무일수\r\n");
      out.write("					$(\"#workhour\").text(arrwhData[1]); // 총근무시간 - 시간\r\n");
      out.write("					$(\"#workmin\").text(arrwhData[2]);  //  총근무시간 - 분\r\n");
      out.write("				}					\r\n");
      out.write("				\r\n");
      out.write("				function whenError(e){\r\n");
      out.write("					alert(JSON.stringify(e));\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			// 올해 근무 정보 - 근무시간<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\r\n");
      out.write("			\r\n");
      out.write("			// 근무현황 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\r\n");
      out.write("			function worknow() {\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"workSelect.tr\",\r\n");
      out.write("					type: \"Get\",\r\n");
      out.write("					data: {	mnum: $(\"#mnum\").val()},\r\n");
      out.write("					success: whenSuccess,\r\n");
      out.write("					error: whenError\r\n");
      out.write("				}); // end of ajax : 근무현황\r\n");
      out.write("				\r\n");
      out.write("				//whData : dayNhour\r\n");
      out.write("				function whenSuccess(wnData) {	\r\n");
      out.write("					$('#wndiv').load(location.href+' #wntable');\r\n");
      out.write("				}					\r\n");
      out.write("				\r\n");
      out.write("				function whenError(e){\r\n");
      out.write("					alert(JSON.stringify(e));\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			// 근무현황 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\r\n");
      out.write("			\r\n");
      out.write("			$(document).on('click', '.vacApp', function(){\r\n");
      out.write("				location.href=\"appInsertForm/V.tr\";\r\n");
      out.write("			});\r\n");
      out.write("		});	// end of $(document).ready(function(){});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("			.t_out{\r\n");
      out.write(" 				border: 2px solid #cccccc;\r\n");
      out.write("				border-radius: 5px;\r\n");
      out.write("				width: 95%;\r\n");
      out.write("				height: 95%;\r\n");
      out.write("				margin-left:auto;\r\n");
      out.write("				margin-right:auto;\r\n");
      out.write("				absolute;\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			.div1{\r\n");
      out.write("				float: left; \r\n");
      out.write("				width: 33%;\r\n");
      out.write("				height: 250px;\r\n");
      out.write("			}\r\n");
      out.write("			.div2{\r\n");
      out.write("				float: left; \r\n");
      out.write("				width: 33%;\r\n");
      out.write("				height: 400px;\r\n");
      out.write("			}\r\n");
      out.write("			.timer_tr{\r\n");
      out.write("				align-content:center;\r\n");
      out.write("			}\r\n");
      out.write("			thead, td{\r\n");
      out.write("				text-align:center;\r\n");
      out.write("			}\r\n");
      out.write("			td{\r\n");
      out.write("				vertical-align:top;\r\n");
      out.write("			}\r\n");
      out.write("			th{\r\n");
      out.write("				height:50px;\r\n");
      out.write("				font-size:20px;\r\n");
      out.write("			}\r\n");
      out.write("			.td_0{\r\n");
      out.write("				width:20%;\r\n");
      out.write("			}\r\n");
      out.write("			.td_1{\r\n");
      out.write("				vertical-align:middle;\r\n");
      out.write("				width: 33%;\r\n");
      out.write("			}\r\n");
      out.write("			.hl{\r\n");
      out.write("				text-decoration-line:none;\r\n");
      out.write("			}\r\n");
      out.write("			.td_3, .td_4{\r\n");
      out.write("				height : 15px;\r\n");
      out.write("			}\r\n");
      out.write("			.tn{\r\n");
      out.write("				font-weight:bold;\r\n");
      out.write("				font-size: 30px;\r\n");
      out.write("			}\r\n");
      out.write("			.st{\r\n");
      out.write("				margin : 0 ;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.wchkBtn2{\r\n");
      out.write("				width: 100px;\r\n");
      out.write("				height: 40px;\r\n");
      out.write("				font-size: 17px;\r\n");
      out.write("				font-weight:bold;\r\n");
      out.write("				background-color: #92D050;\r\n");
      out.write("				border: 2px #C5E0B4 solid;\r\n");
      out.write("				border-radius:10px;\r\n");
      out.write("				cursor:pointer;\r\n");
      out.write("				color:black;\r\n");
      out.write("			}\r\n");
      out.write("			#vaBtn{\r\n");
      out.write("				width: 90px;\r\n");
      out.write("				height: 40px;\r\n");
      out.write("				font-size: 17px;\r\n");
      out.write("				font-weight:bold;\r\n");
      out.write("				background-color: #92D050;\r\n");
      out.write("				border: 2px #C5E0B4 solid;\r\n");
      out.write("			}\r\n");
      out.write("		</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-dark sticky-top\" style=\"background-color: #C5E0B4;padding-right:0;\">\r\n");
      out.write("		<!--LOGO-->\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"/tr_spring/mainPage.tr\" >&nbsp&nbsp<img src=\"../tr_spring/resources/images/logo-green2.png\" style=\"height:30px\"></a>\r\n");
      out.write("		<!--Links-->\r\n");
      out.write("		<div class=\"container-fluid full-width\">\r\n");
      out.write("		<ul class=\"nav navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a class=\"nav-link dropdown-toggle\" id=\"dropdown01\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"padding-top:13px;font-size:18px;color:#534825;font-weight:bold;cursor:pointer\">인사</a>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/mainPage.tr\">메인페이지</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tBoardSelectAll.tr\">게시판</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tMemAddrBook.tr\">주소록</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/appSelect/A.tr\">전자결재</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"#\">일정</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/workSelect.tr\">인사</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div>\r\n");
      out.write("						<div class=\"dropdown\" style=\"position:absolute;right:80px\">\r\n");
      out.write("				<img id=\"bell\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\" src=\"/tr_spring/resources/images/notification-bell.png\" alt=\"\" width=\"32\" height=\"32\" style=\"cursor:pointer\">\r\n");
      out.write("			</div>\r\n");
      out.write("		<div>\r\n");
      out.write("		<div class=\"dropdown\" style=\"left:-10px;cursor:pointer\">\r\n");
      out.write("			<a href=\"#\" class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle dropdown-toggle-no-caret\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			  <img src=\"fileupload/tmem/");
      out.print( mvo.getMphoto() );
      out.write("\" alt=\"\" width=\"35\" height=\"35\" class=\"rounded-circle me-2\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\" style=\"left:-110px\" aria-labelledby=\"dropdownUser1\">\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"#\">마이 페이지</a></li>\r\n");
      out.write("			  <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"terraLogout.tr\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("		<div class=\"row\" style=\"margin-right: 0;\">\r\n");
      out.write("		  <div class=\"col-3\" >\r\n");
      out.write("			<!-- 사이드바 내용 -->\r\n");
      out.write("			<div class=\"sidebar\">\r\n");
      out.write("			  <!-- 사이드바 내용을 추가 -->\r\n");
      out.write("			  <div class=\"d-flex flex-column flex-shrink-0 p-3 \" style=\"width: 280px; height:auto; overflow-y: auto; height: 100vh;position:fixed; background-color:#E2F0D9;\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary vacApp\" id=\"istBtn\" style=\"background-color:#92D050;height:50px;border:0; font-size:20px;font-weight:1000;color:#534825;cursor:pointer\">+ 휴가신청</button>\r\n");
      out.write("				<br>\r\n");
      out.write("				<ul class=\"list-unstyled ps-0\">\r\n");
      out.write("					<li class=\"mb-1\">\r\n");
      out.write("					  <button class=\"btn btn-toggle align-items-center rounded collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#home-collapse\" aria-expanded=\"true\" style=\"font-size: 20px;cursor:pointer\">\r\n");
      out.write("						근무\r\n");
      out.write("					  </button>\r\n");
      out.write("					  <div class=\"collapse show\" id=\"home-collapse\">\r\n");
      out.write("						<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("						  <li><div class=\"idx\" id=\"nowSelected\" onclick=\"javascript:location.href='/tr_spring/workSelect.tr'\"><img src=\"/tr_spring/resources/images/documents.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">근무현황</span></div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</li>\r\n");
      out.write("				  </ul>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		  <div class=\"col-9\" style=\"left:400px;margin-top:60px\">\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("			  <!-- 본문 내용을 추가 -->\r\n");
      out.write("<form name=\"trForm\" id=\"trForm\">\r\n");
      out.write("	<!-- 테스트용 사원번호 M20230001 -->\r\n");
      out.write("	<input type=\"hidden\" name=\"mnum\" id=\"mnum\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"wnum\" id=\"wnum\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"startdate\" id=\"startdate\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"enddate\" id=\"enddate\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"deleteyn\" id=\"deleteyn\" value=\"Y\">\r\n");
      out.write("	<input type=\"hidden\" name=\"insertdate\" id=\"insertdate\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"updatedate\" id=\"updatedate\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"wchange\" id=\"wchange\" value=\"\">\r\n");
      out.write("	<!-- DIV 시작 -->\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("	<h4>올해 근무 정보</h4>\r\n");
      out.write("		<div class=\"d_top\" id=\"dtop\">\r\n");
      out.write("		<!--근태 현황-->\r\n");
      out.write("		<div class=\"div1\" id=\"Etcdiv\">\r\n");
      out.write("			<table class=\"t_out\" id=\"Etctbl\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"4\" rowspan=\"2\">근태현황<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>					\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>				\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_0\">\r\n");
      out.write("							<br>\r\n");
      out.write("							<p class=\"ss\">지각</p>\r\n");
      out.write("							<span id=\"late\">0</span>회\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_0\">\r\n");
      out.write("						<br>\r\n");
      out.write("							<p class=\"ss\">조기퇴근</p>\r\n");
      out.write("							<span id=\"early\">0</span>회\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_0\">	\r\n");
      out.write("						<br>\r\n");
      out.write("							<p class=\"ss\">퇴근미체크</p>\r\n");
      out.write("							<span id=\"notchk\">0</span>회\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_0\">\r\n");
      out.write("						<br>\r\n");
      out.write("							<p class=\"ss\">결근</p>\r\n");
      out.write("							<span id=\"absence\">0</span>회\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>						\r\n");
      out.write("				</tbody>				\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--휴가 현황-->\r\n");
      out.write("		<div class=\"div1\">\r\n");
      out.write("			<table class=\"t_out\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"3\">휴가현황<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>	\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_1\">\r\n");
      out.write("							<p class=\"ss\">잔여휴가</p>\r\n");
      out.write("							<input 	type=\"text\" id=\"restvacation\" value=\"\" align=\"center\" \r\n");
      out.write("									style=\"border:none;border-right:0px; border-top:0px; boder-left:0px; boder-bottom:0px; width:25px;font-size:20px;\" readonly> 일\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_1\">\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_1\" style=vertical-align:middle;>\r\n");
      out.write("							<span class=\"vacApp\"style=\"font-weight:bold;font-size:20px;color:#92D050;cursor:pointer\">휴가 신청</span>	\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr >\r\n");
      out.write("						<td colspan=\"3\">\r\n");
      out.write("							<br>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>				\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--근무시간-->\r\n");
      out.write("		<div class=\"div1\">\r\n");
      out.write("			<table class=\"t_out\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"2\">근무시간<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>					\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_1\">\r\n");
      out.write("							<p class=\"ss\">근무일수</p>\r\n");
      out.write("							<span id=\"workday\">0</span><span>일</span>\r\n");
      out.write("							<br><br><br>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_1\">\r\n");
      out.write("							<p class=\"ss\">총근무시간</p>\r\n");
      out.write("							<span id=\"workhour\">0</span><span>시간</span><span id=\"workmin\">0</span><span>분</span>\r\n");
      out.write("							<br><br><br>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>				\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 아래칸 -->\r\n");
      out.write("	<div class=\"main2\" >\r\n");
      out.write("	<div>\r\n");
      out.write("	<h4>오늘 근무 현황</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--근무 체크-->\r\n");
      out.write("		<div class=\"div2\">\r\n");
      out.write("			<table class=\"t_out\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"4\">근무체크<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>				\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr id=\"timer_tr\">\r\n");
      out.write("						<td colspan=\"3\">\r\n");
      out.write("							<span class=\"tn\" id=\"timetxt\">현재시각 : </span>\r\n");
      out.write("							<span class=\"tn\" id=\"timer\"> </span>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"3\">\r\n");
      out.write("						<!-- 출근 : come to work -->\r\n");
      out.write("							<hr style=\"width:90%;\">\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sCtw\" value=\"출근하기\">\r\n");
      out.write("							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sLto\" value=\"퇴근하기\">\r\n");
      out.write("							<br>\r\n");
      out.write("							<hr style=\"width:90%;\">\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sWork\" value=\"업무\">\r\n");
      out.write("							&nbsp;&nbsp;\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sOut\" value=\"외출\">\r\n");
      out.write("							&nbsp;&nbsp;\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sCon\" value=\"회의\"><br><br>\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sWo\" value=\"외근\">\r\n");
      out.write("							&nbsp;&nbsp;\r\n");
      out.write("							<input type=\"button\" class=\"btn btn-primary wchkBtn2\" style=\"background-color:#92D050;border-color:#92D050;width:100px;\" name=\"wstate\" id=\"sElto\" value=\"조퇴\">\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>				 \r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- SELECT 데이터 가져오기 -->		\r\n");
      out.write("		<!--근무 현황-->\r\n");
      out.write("		<!--게시판 셀렉트 올처럼 표시해야해....-->\r\n");
      out.write("		<div class=\"div2\" id=\"wndiv\">\r\n");
      out.write("			<table class=\"t_out\" id=\"wntable\">\r\n");
      out.write("			<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"2\">근무현황<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_3\">\r\n");
      out.write("							<p class=\"st\">시간</p>\r\n");
      out.write("							<hr style=\"width:75%;\">\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_3\">\r\n");
      out.write("							<p class=\"st\">상태</p>\r\n");
      out.write("							<hr style=\"width:75%;\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"wnbody\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\">\r\n");
 
		
	if(wnchk !=  null){
		String worknow_1 = (String)request.getAttribute("datashift");
		
		// 넘어온 데이터 1차 split => 시간,상태코드 형태
		worknow_2 = worknow_1.split("~");
	
		wlen = worknow_2.length;
		System.out.println("trWorkForm | wlen 체크 | " + wlen );
		System.out.println("trWorkForm | wlen 체크 | worknow_2[0] | " + worknow_2[0]);
		
//		int j = 0;
//		int k = 0;
		int i=0;
		for (i=0; i < wlen; i++) {

			s_work = worknow_2[i].split(",");
			//01:업무, 02:외근, 03:외출, 04:회의, 05:퇴근
			String txtcng = s_work[1];
			
			if(txtcng.equals("01")){
				// 출근|업무 구분 넣어야함>>>>>>>>>>>>>>>> 출퇴근 9 to 6 가정
				if (i==0){
					s_work[1] = s_work[1].replace("01", "출근");
				}else{
					s_work[1] = s_work[1].replace("01", "업무");	
				}	
			}else if(txtcng.equals("02")){
				s_work[1] = s_work[1].replace("02", "외근");
			}else if(txtcng.equals("03")){
				s_work[1] = s_work[1].replace("03", "외출");
			}else if(txtcng.equals("04")){
				s_work[1] = s_work[1].replace("04", "회의");
			}else if(txtcng.equals("05")){
				s_work[1] = s_work[1].replace("05", "퇴근");
			}
			logger.info("trWorkForm | s_work[0] | {}",s_work[0]);
			logger.info("trWorkForm | s_work[1] | {}",s_work[1]);		
			

      out.write("\r\n");
      out.write("			\r\n");
      out.write("				<span>");
      out.print(s_work[0]);
      out.write("\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				");
      out.print(s_work[1]);
      out.write("&nbsp;<br></span>\r\n");
      out.write("			\r\n");

		}
	}
	System.out.println("근무현황 출력 종료 =============================");

      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>							\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 근무 통계-->\r\n");
      out.write("		<div class=\"div2\">\r\n");
      out.write("			<table class=\"t_out\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"2\">근무통계<br><hr style=\"width:90%;\"></th>\r\n");
      out.write("					</tr>			\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><img id=\"chul\" src=\"fileupload/sigak/chulgeun.png\" style=\"width:400px;height:300px\"></td>\r\n");
      out.write("					</tr>				\r\n");
      out.write("				</tbody>				\r\n");
      out.write("			</table>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<script src=\"/tr_spring/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
