/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-03 07:59:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraMain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kos.tr.member.vo.TerraMemberVO;
import java.util.List;
import java.util.ArrayList;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.json.simple.parser.JSONParser;
import java.util.Map;
import java.util.HashMap;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.json.simple.parser.JSONParser");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Logger logger = LogManager.getLogger(this.getClass());
	String mnum = (String)request.getAttribute("mnum"); 
	ArrayList<TerraMemberVO> uList = (ArrayList<TerraMemberVO>)request.getAttribute("uList");
	String mname = (String)request.getAttribute("mname");
	TerraMemberVO mvo = uList.get(0);

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maxinum-scale=1, user-scalable=no\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../tr_spring/resources/css/sidebars.css\">\r\n");
      out.write("	<link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/sidebars/\">\r\n");
      out.write("	<script src=\"../tr_spring/resources/js/util.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"resources/css/main.css\">\r\n");
      out.write("    <title>TerraGroupMain</title>\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("	.icon_img{\r\n");
      out.write("		width:22px;\r\n");
      out.write("		height: 22px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		margin-left: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write(" 	.dropdown-toggle-no-caret::after { \r\n");
      out.write(" 		display: none; \r\n");
      out.write(" 	} \r\n");
      out.write("\r\n");
      out.write(" 	th{ \r\n");
      out.write("		background-color:#E2F0D9;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	td{\r\n");
      out.write("		text-align:center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.subj{\r\n");
      out.write("		width:400px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#nowSelected{\r\n");
      out.write("		background-color: #C5E0B4;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	\r\n");
      out.write("        $(function(){\r\n");
      out.write("            // 현재 시간 \r\n");
      out.write("            function printTime(){\r\n");
      out.write("            	let days = [\"일\", \"월\", \"화\", \"수\", \"목\", \"금\", \"토\"];\r\n");
      out.write("                let md = new Date();\r\n");
      out.write("                \r\n");
      out.write("                let mm = md.getMonth() + 1;\r\n");
      out.write("				let dd = md.getDate();\r\n");
      out.write("				let ii = md.getDay();\r\n");
      out.write("				let di = days[ii];\r\n");
      out.write("                let hh = md.getHours();\r\n");
      out.write("                let mi = md.getMinutes();\r\n");
      out.write("                let ss = md.getSeconds();\r\n");
      out.write("\r\n");
      out.write("                let day = \r\n");
      out.write("                		  numpad(mm) + \"월 \" +\r\n");
      out.write("						  numpad(dd) + \"일 \" +\r\n");
      out.write("						  \" (\"+ di + \")            \" ;\r\n");
      out.write("                \r\n");
      out.write("                let time = \r\n");
      out.write("                		numpad(hh) + \":\" +\r\n");
      out.write("                        numpad(mi) + \":\" +\r\n");
      out.write("                        numpad(ss);\r\n");
      out.write("                document.getElementById(\"timer\").innerHTML = time;\r\n");
      out.write("                $('#day').html(day);\r\n");
      out.write("            }\r\n");
      out.write("            setInterval(printTime, 1000);\r\n");
      out.write("\r\n");
      out.write("            function numpad(num) {\r\n");
      out.write("                return (num < 10 ? \"0\" + num : num);\r\n");
      out.write("            }\r\n");
      out.write("          \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("     // 버튼 클릭 이벤트 핸들러\r\n");
      out.write("        $('button[name=\"status\"]').click(function() {\r\n");
      out.write("            var statusText = $(this).text();  // 클릭한 버튼의 텍스트 가져오기\r\n");
      out.write("            $('#status').text(statusText);    // 상태 텍스트 업데이트\r\n");
      out.write("        	\r\n");
      out.write("            // 이전에 클릭된 버튼에서 'active' 클래스 제거\r\n");
      out.write("            if (lastClickedButton !== null) {\r\n");
      out.write("                lastClickedButton.removeClass('active');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 현재 클릭된 버튼에 'active' 클래스 추가\r\n");
      out.write("            $(this).addClass('active');\r\n");
      out.write("            lastClickedButton = $(this);\r\n");
      out.write("        });\r\n");
      out.write("     \r\n");
      out.write("    	 // 초기 상태 텍스트와 클릭된 버튼 초기화\r\n");
      out.write("        var initialStatusText = $('#status').text();\r\n");
      out.write("        if (initialStatusText !== '') {\r\n");
      out.write("            lastClickedButton = $('button[name=\"status\"]').filter(function() {\r\n");
      out.write("                return $(this).text() === initialStatusText;\r\n");
      out.write("            });\r\n");
      out.write("            lastClickedButton.addClass('active');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        $(document).on('click', '#come', function(){\r\n");
      out.write("        	\r\n");
      out.write("        	$('.businesstb').css('display','block');\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("		$(document).on('click', '#gone', function(){\r\n");
      out.write("        	\r\n");
      out.write("        	$('.businesstb').css('display','none');\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // 업무 버튼 클릭 이벤트\r\n");
      out.write("        $(\"#work\").click(function() {\r\n");
      out.write("            $(\"#status\").text(\"업무\");\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 외출 버튼 클릭 이벤트\r\n");
      out.write("        $(\"#goout\").click(function() {\r\n");
      out.write("            $(\"#status\").text(\"외출\");\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 회의 버튼 클릭 이벤트\r\n");
      out.write("        $(\"#meeting\").click(function() {\r\n");
      out.write("            $(\"#status\").text(\"회의\");\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 외근 버튼 클릭 이벤트\r\n");
      out.write("        $(\"#outoffice\").click(function() {\r\n");
      out.write("            $(\"#status\").text(\"외근\");\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        // 로그아웃 버튼\r\n");
      out.write("        $(document).on(\"click\", \"#logout\", function(){\r\n");
      out.write("			alert(\"계정 로그아웃 합니다.\");\r\n");
      out.write("			location.href=\"logout.tr\";\r\n");
      out.write("		});\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function callToMain() {\r\n");
      out.write("			\r\n");
      out.write("			$('#trMainForm').attr({\r\n");
      out.write("				'action':'loginForm.tr',\r\n");
      out.write("				'method':'GET',\r\n");
      out.write("				'enctype':'multipart/form-data'\r\n");
      out.write("			}).submit();				\r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"GET\",\r\n");
      out.write("			url: '/tr_spring/appAlert.tr',\r\n");
      out.write("			success : function(result){\r\n");
      out.write("				\r\n");
      out.write("				if (result == 'ALERT_YES') {\r\n");
      out.write("					$('#bell').attr(\"src\", \"/tr_spring/resources/images/alert.png\")\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xtr, status, error){\r\n");
      out.write("				alert(xtr + \":\" + status + \":\" + error);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#cbtn', function(){\r\n");
      out.write("			\r\n");
      out.write("			window.open('http://192.168.0.25:3000/', '캘린더', 'width=600,height=600,left=300,top=100');\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		openPopup();\r\n");
      out.write("		function openPopup() {\r\n");
      out.write("\r\n");
      out.write("			  window.open('mainNotice.tr', '공지사항', 'width=410,height=540,left=300,top=300');\r\n");
      out.write("			}\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-dark sticky-top\" style=\"background-color: #C5E0B4;padding-right:0;\">\r\n");
      out.write("		<!--LOGO-->\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"/tr_spring/mainPage.tr\" >&nbsp&nbsp<img src=\"../tr_spring/resources/images/logo-green2.png\" style=\"height:30px\"></a>\r\n");
      out.write("		<!--Links-->\r\n");
      out.write("		<div class=\"container-fluid full-width\">\r\n");
      out.write("		<ul class=\"nav navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a class=\"nav-link dropdown-toggle\" id=\"dropdown01\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"padding-top:13px;font-size:18px;color:#534825;font-weight:bold;cursor:pointer\">메인 페이지</a>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdown01\" >\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/mainPage.tr\">메인페이지</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tBoardSelectAll.tr\">게시판</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tMemAddrBook.tr\">주소록</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/appSelect/A.tr\">전자결재</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"#\">일정</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/workSelect.tr\">인사</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div>\r\n");
      out.write("						<div class=\"dropdown\" style=\"position:absolute;right:80px\">\r\n");
      out.write("				<img id=\"bell\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\" src=\"/tr_spring/resources/images/notification-bell.png\" alt=\"\" width=\"32\" height=\"32\" style=\"cursor:pointer\">\r\n");
      out.write("			</div>\r\n");
      out.write("		<div>\r\n");
      out.write("		<div class=\"dropdown\" style=\"left:-10px;cursor:pointer\">\r\n");
      out.write("			<a href=\"#\" class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle dropdown-toggle-no-caret\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			  <img src=\"../tr_spring/fileupload/tmem/");
      out.print( mvo.getMphoto() );
      out.write("\" alt=\"\" width=\"35\" height=\"35\" class=\"rounded-circle me-2\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\" style=\"left:-110px\" aria-labelledby=\"dropdownUser1\">\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"#\">마이 페이지</a></li>\r\n");
      out.write("			  <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"terraLogout.tr\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("  <form name=\"trMainForm\" id=\"trMainForm\">\r\n");
      out.write("       <div class=\"all\" style=\"background-color:#f2f2f2\">\r\n");
      out.write("        <div class=\"s\">\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            		");

            	
				   	for(int i=0; i < uList.size(); i++){
					    		
					    	TerraMemberVO trvo = (TerraMemberVO)uList.get(i);
					    	
					
      out.write("	\r\n");
      out.write("					");
 
						String mposition = trvo.getMposition();
						
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<img class=\"img\" src=\"fileupload/tmem/");
      out.print( mvo.getMphoto() );
      out.write("\" id=\"imageClick\"> <br>\r\n");
      out.write("					<h2 class=\"name\" style=\"left:60px\">");
if (mposition.equals("06")) {
					    out.print("대표이사");
					} else if (mposition.equals("05")) {
					    out.print("이사");
					} else if (mposition.equals("04")) {
					    out.print("과장");
					} else if (mposition.equals("03")) {
					    out.print("차장");
					} else if (mposition.equals("02")) {
					    out.print("대리");
					} else if (mposition.equals("01")) {
					    out.print("사원");
					}
      out.write(' ');
      out.print( trvo.getMname() );
      out.write("</h2><br>\r\n");
      out.write("					\r\n");
      out.write("					<button class=\"logout\" id=\"logout\" name=\"logout\" >로그아웃</button>\r\n");
      out.write("									\r\n");
      out.write("				");

					}//end of if
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("               <div class=\"time-box\">\r\n");
      out.write("				    <div class=\"time\">\r\n");
      out.write("				        <table class=\"timetb\" style=\"text-align:left;width:300px;height:150px\">\r\n");
      out.write("				            <tr>\r\n");
      out.write("				                <td>\r\n");
      out.write("				                    <span class=\"timebold\" id=\"day\" style=\"font-size:13px;width:200px\"></span><br>\r\n");
      out.write("				                	<span class=\"timebold\" id=\"timer\" style=\"font-size:23px;width:200px\"></span>\r\n");
      out.write("				                </td>\r\n");
      out.write("				                <td style=\"width:100px;\"><span class=\"timebold\" id=\"status\">출근전</span></td>\r\n");
      out.write("				            </tr>\r\n");
      out.write("				        </table>\r\n");
      out.write("				        \r\n");
      out.write("				        <div class=\"business\">\r\n");
      out.write("						    <table>\r\n");
      out.write("						    <thead class=\"businessgo\">\r\n");
      out.write("						      <tr>\r\n");
      out.write("				        <td>\r\n");
      out.write("				        	<button class=\"but\" type=\"button\" name=\"come\" id=\"come\" value=\"\">출근</button>\r\n");
      out.write("				        </td>\r\n");
      out.write("				        <td>\r\n");
      out.write("				        	<button class=\"but\" type=\"button\" name=\"gone\" id=\"gone\" value=\"\">퇴근</button>\r\n");
      out.write("				        </td>\r\n");
      out.write("				        </tr>\r\n");
      out.write("						    </thead>\r\n");
      out.write("						    <tbody class=\"businesstb\" style=\"display:none\">\r\n");
      out.write("						        <tr>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" name=\"status\" id=\"work\" value=\"\">업무</button>\r\n");
      out.write("						            </td>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" name=\"status\" id=\"goout\" value=\"\">외출</button>\r\n");
      out.write("						            </td>\r\n");
      out.write("						        </tr>\r\n");
      out.write("						        <tr>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" name=\"status\" id=\"meeting\" value=\"\">회의</button>\r\n");
      out.write("						            </td>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" name=\"status\" id=\"outoffice\" value=\"\">외근</button>\r\n");
      out.write("						            </td>\r\n");
      out.write("						        </tr>\r\n");
      out.write("						        </tbody>\r\n");
      out.write("						    </table>\r\n");
      out.write("						</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"approval-box\">\r\n");
      out.write("				       <div class=\"approval\">\r\n");
      out.write("						    <table >\r\n");
      out.write("						    <tbody class=\"approvaltb\">\r\n");
      out.write("						        <tr>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" onclick=\"location.href='appSelect/W.tr'\" name=\"wait\" id=\"wait\" value=\"대기\">대기</button>\r\n");
      out.write("						             </td>\r\n");
      out.write("						             <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" onclick=\"location.href='appSelect/AA.tr'\" name=\"check\" id=\"check\" value=\"확인\">확인</button>\r\n");
      out.write("						             </td>\r\n");
      out.write("						             </tr>\r\n");
      out.write("						            <tr>\r\n");
      out.write("						            <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" onclick=\"location.href='appSelect/P.tr'\" name=\"expect\" id=\"expect\" value=\"예정\">예정</button>\r\n");
      out.write("						                </td>\r\n");
      out.write("						                <td>\r\n");
      out.write("						                <button class=\"but\" type=\"button\" onclick=\"location.href='appSelect/K.tr'\" name=\"progress\" id=\"progress\" value=\"진행\">진행</button>\r\n");
      out.write("						                </td>\r\n");
      out.write("						        </tr>\r\n");
      out.write("						        </tbody>\r\n");
      out.write("						    </table>\r\n");
      out.write("						</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				");
 
				    // mposition 값 가져오기
				    String mposition = "";
				    if (uList != null && !uList.isEmpty()) {
				        TerraMemberVO trvo = uList.get(0); // 첫 번째 사용자 정보만 가져옴
				        mposition = trvo.getMposition();
				    }
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("          <!--  \r\n");
      out.write("          \r\n");
      out.write("                -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"main\" style=\"background-color:white\">\r\n");
      out.write("				<ul class=\"dep1\" style=\"width:1045px\">\r\n");
      out.write("                    <li style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px;\">\r\n");
      out.write("                    	<a href=\"/tr_spring/tBoardSelectAll.tr\">\r\n");
      out.write("                        	<img src=\"resources/images/boardMain.png\" alt=\"게시판\" style=\"width:50px;margin-top:10px;opacity:0.6\"><br>\r\n");
      out.write("                        	<span style=\"font-weight:bold\">게시판</span>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    </li>                  \r\n");
      out.write("                    <li style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px\">\r\n");
      out.write("                    	<a href=\"/tr_spring/tMemAddrBook.tr\">\r\n");
      out.write("                        	<img src=\"resources/images/people.png\" alt=\"주소록\" style=\"width:50px;margin-top:12px;opacity:0.6\"><br>\r\n");
      out.write("                        	<span style=\"font-weight:bold\">주소록</span>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("            \r\n");
      out.write("                    <li style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px\">\r\n");
      out.write("                    	<a href=\"/tr_spring/appSelect/A.tr\">\r\n");
      out.write("                       		<img src=\"resources/images/app.png\" alt=\"전자결재\" style=\"width:50px;margin-top:12px;margin-left:5px;opacity:0.6\"><br>\r\n");
      out.write("                   			<span style=\"font-weight:bold\">전자결재</span>\r\n");
      out.write("                   		</a>\r\n");
      out.write("                   	</li>\r\n");
      out.write("        \r\n");
      out.write("                    <li style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px\">\r\n");
      out.write("                    	<a href=\"/tr_spring/workSelect.tr\">\r\n");
      out.write("                        	<img src=\"resources/images/work.png\" alt=\"인사\" style=\"width:50px;margin-top:12px;opacity:0.6\"><br>\r\n");
      out.write("                        	<span style=\"font-weight:bold\">인사</span>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li id=\"cbtn\" style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px\">\r\n");
      out.write("                        	<img src=\"resources/images/calender.png\" alt=\"일정\" style=\"width:50px;margin-top:12px;opacity:0.6\"><br>\r\n");
      out.write("                        	<span style=\"font-weight:bold\">일정</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                	\r\n");
      out.write("                	");
      out.write("\r\n");
      out.write("                	");
 if (mposition.equals("06")) { 
      out.write("\r\n");
      out.write("	                    <li style=\"background-color:white;border-radius: 50%;height:100px;width:100px;margin-right:30px\">\r\n");
      out.write("	                    	<a href=\"/tr_spring/tMemSelectAll.tr\">\r\n");
      out.write("	                        	<img src=\"resources/images/member.png\" alt=\"직원관리\" style=\"width:50px;margin-top:10px;margin-left:7px;opacity:0.6\"><br>\r\n");
      out.write("	                        	<span style=\"font-weight:bold\">사원관리</span>\r\n");
      out.write("	                    	</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			<div style=\"top:150px;position:absolute\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mainMoney.jsp", out, false);
      out.write("</div>\r\n");
      out.write("			<div style=\"left:515px;top:450px;position:absolute\"><iframe src=\"http://192.168.0.25:3000/\" width=530px height=500px frameborder=\"0\"></iframe></div>\r\n");
      out.write("			<div style=\"top:355px;left:-42px;position:absolute\"><iframe src=\"http://192.168.0.25:3008/\" width=\"600px\" height=\"600px\" frameborder=\"0\"></iframe></div>\r\n");
      out.write("		</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("    </form>\r\n");
      out.write("    <script src=\"/tr_spring/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
