/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-04 08:22:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraApproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.If;
import com.kos.tr.app.vo.AppDraftVO;
import com.kos.tr.member.vo.TerraMemberVO;
import com.kos.tr.common.CodeUtil;
import java.util.ArrayList;
import com.kos.tr.common.T_Session;
import java.util.Arrays;

public final class appSelectContent_005fD_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.If");
    _jspx_imports_classes.add("com.kos.tr.common.T_Session");
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("com.kos.tr.app.vo.AppDraftVO");
    _jspx_imports_classes.add("com.kos.tr.common.CodeUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<TerraMemberVO> aList = (ArrayList<TerraMemberVO>)request.getAttribute("aList"); // 결재자들의 정보 조회
	ArrayList<TerraMemberVO> bList = (ArrayList<TerraMemberVO>)request.getAttribute("bList"); // 참조자들의 정보 조회
	ArrayList<AppDraftVO> cList = (ArrayList<AppDraftVO>)request.getAttribute("cList"); // 문서정보
	ArrayList<TerraMemberVO> uList = (ArrayList<TerraMemberVO>)request.getAttribute("uList"); // 사용자 정보 조회
	ArrayList<TerraMemberVO> pList = (ArrayList<TerraMemberVO>)request.getAttribute("pList"); // 대결 맡긴 사람 정보 조회
	String passYN = (String) request.getAttribute("passYN");
	
	
	TerraMemberVO mvo = uList.get(0);
	int uplevel = Integer.parseInt(cList.get(0).getAlevel()) + 1 ;
	String step = CodeUtil.nowStep(cList.get(0).getAlevel(), cList.get(0).getAapp(), uList.get(0).getMnum());
	AppDraftVO advo = cList.get(0);
	String app[] = advo.getAapp().split(",");
	
	
	ArrayList<String> eList = new ArrayList<String>(Arrays.asList(app));
	
	int f = eList.indexOf(uList.get(0).getMnum());
	int j = 0;
	if(pList != null){
		j =  eList.indexOf(pList.get(0).getMnum());
	}
	String[] confirm = cList.get(0).getAconfirm().split(",");
	String ref = "";
	
	for (int i=0; i < bList.size(); i++){ 
		ref += bList.get(i).getMname() + " ";
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("	<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maxinum-scale=1, user-scalable=no\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/sidebars.css\">\r\n");
      out.write("	<link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/sidebars/\">\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	.icon_img{\r\n");
      out.write("		width:22px;\r\n");
      out.write("		height: 22px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		margin-left: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dropdown-toggle-no-caret::after {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}		\r\n");
      out.write("	.initial-size {\r\n");
      out.write("	  	min-height: 200px; \r\n");
      out.write("	  	width : 1000px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("	.idx{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	table {\r\n");
      out.write("	 border-collapse: collapse;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	table, tr, td{\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		border:1px solid black ;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	td{\r\n");
      out.write("		width:130px;\r\n");
      out.write("		height:60px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.mpo{\r\n");
      out.write("		background-color:#E2F0D9;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		font-weight:bold;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		if (");
      out.print(f);
      out.write(" == -1 || ");
      out.print(Integer.parseInt(cList.get(0).getAlevel()));
      out.write(" == 9) {\r\n");
      out.write("			$('#btnshow').css('display','none');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if ('");
      out.print(step);
      out.write("' != '대기') {\r\n");
      out.write("			$('#reject').css('display','none');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#istBtn', function(){\r\n");
      out.write("			location.href = \"../appInsertDoc.tr\";\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		$(document).on('mouseenter', '.idx', function(){\r\n");
      out.write("\r\n");
      out.write("			$(this).css('background-color', '#ecf9ec');\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(document).on('mouseleave', '.idx', function(){\r\n");
      out.write("\r\n");
      out.write("			$(this).css('background-color', '#E2F0D9');\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('mouseleave', '#nowSelected', function(){\r\n");
      out.write("\r\n");
      out.write("			$(this).css('background-color', '#C5E0B4');\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		if ('");
      out.print(passYN);
      out.write("' == 'Y') {\r\n");
      out.write("			\r\n");
      out.write("			$('#passY').css(\"display\" , \"block\");\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var aconfirm = \"\";\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#approval', function() {\r\n");
      out.write("\r\n");
      out.write("			if ('");
      out.print(step);
      out.write("' == '대기') {\r\n");
      out.write("				var num = $('#alevel').val('");
      out.print(uplevel);
      out.write("');\r\n");
      out.write("				\r\n");
      out.write("				for (var i = 0; i < 5; i++) {\r\n");
      out.write("					var cVal = $('.confirms').eq(i).val();\r\n");
      out.write("					var cValCk = cVal ?? '`';\r\n");
      out.write("					\r\n");
      out.write("					if ('");
      out.print(uList.get(0).getMnum());
      out.write("' ===  cVal) {\r\n");
      out.write("						aconfirm += \"");
      out.print(uList.get(0).getMnum());
      out.write("\" + \",\";					\r\n");
      out.write("					}else{\r\n");
      out.write("						aconfirm += cValCk + \",\";	\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				$('#aconfirm').val(aconfirm);\r\n");
      out.write("				console.log($('#aconfirm').val());\r\n");
      out.write("				\r\n");
      out.write("				$('#sangsinForm').attr({\r\n");
      out.write("					'action':'/tr_spring/appSangsinUpdate.tr',    \r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if ('");
      out.print(step);
      out.write("' == '예정') {\r\n");
      out.write("				for (var i = 0; i < 5; i++) {\r\n");
      out.write("					var cVal = $('.confirms').eq(i).val();\r\n");
      out.write("					var cValCk = cVal ?? '`';\r\n");
      out.write("					\r\n");
      out.write("					if ('");
      out.print(uList.get(0).getMnum());
      out.write("' ===  cVal) {\r\n");
      out.write("						aconfirm += \"");
      out.print(uList.get(0).getMnum());
      out.write("\" + \",\";					\r\n");
      out.write("					}else{\r\n");
      out.write("						aconfirm += cValCk + \",\";	\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				$('#aconfirm').val(aconfirm);\r\n");
      out.write("				var nCnt = frequency(aconfirm);\r\n");
      out.write("				var num = $('#alevel').val(parseInt('");
      out.print(uplevel);
      out.write("') + nCnt);\r\n");
      out.write("				\r\n");
      out.write("				$('#sangsinForm').attr({\r\n");
      out.write("					'action':'/tr_spring/appSangsinUpdate.tr',    \r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(document).on('click', '#approvalproxy', function() {\r\n");
      out.write("			\r\n");
      out.write("			");
if(pList != null){
				step = CodeUtil.nowStep(cList.get(0).getAlevel(), cList.get(0).getAapp(), pList.get(0).getMnum());
			}
      out.write("\r\n");
      out.write("			if ('");
      out.print(step);
      out.write("' == '대기') {\r\n");
      out.write("				var num = $('#alevel').val('");
      out.print(uplevel);
      out.write("');\r\n");
      out.write("				\r\n");
      out.write("				for (var i = 0; i < 5; i++) {\r\n");
      out.write("					var cVal = $('.confirms').eq(i).val();\r\n");
      out.write("					var cValCk = cVal ?? '`';\r\n");
      out.write("					\r\n");
      out.write("					if ('");
      out.print(uList.get(0).getMnum());
      out.write("' ===  cVal) {\r\n");
      out.write("						aconfirm += \"");
      out.print(uList.get(0).getMnum());
      out.write("\" + \",\";					\r\n");
      out.write("					}else{\r\n");
      out.write("						aconfirm += cValCk + \",\";	\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("	\r\n");
      out.write("				$('#aconfirm').val(aconfirm);\r\n");
      out.write("				console.log($('#aconfirm').val());\r\n");
      out.write("				$('#sangsinForm').attr({\r\n");
      out.write("					'action':'/tr_spring/appSangsinUpdateProxy.tr',    \r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if ('");
      out.print(step);
      out.write("' == '예정') {\r\n");
      out.write("				for (var i = 0; i < 5; i++) {\r\n");
      out.write("					var cVal = $('.confirms').eq(i).val();\r\n");
      out.write("					var cValCk = cVal ?? '`';\r\n");
      out.write("					\r\n");
      out.write("					if ('");
      out.print(uList.get(0).getMnum());
      out.write("' ===  cVal) {\r\n");
      out.write("						aconfirm += \"");
      out.print(uList.get(0).getMnum());
      out.write("\" + \",\";					\r\n");
      out.write("					}else{\r\n");
      out.write("						aconfirm += cValCk + \",\";	\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				$('#aconfirm').val(aconfirm);\r\n");
      out.write("				var nCnt = frequency(aconfirm);\r\n");
      out.write("				var num = $('#alevel').val(parseInt('");
      out.print(uplevel);
      out.write("') + nCnt);\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				$('#sangsinForm').attr({\r\n");
      out.write("					'action':'/tr_spring/appSangsinUpdateProxy.tr',    \r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#passY', function() {\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < 5; i++) {\r\n");
      out.write("				var cVal = $('.confirms').eq(i).val();\r\n");
      out.write("				var cValCk = cVal ?? '~';\r\n");
      out.write("				\r\n");
      out.write("				if ('");
      out.print(uList.get(0).getMnum());
      out.write("' ===  cVal) {\r\n");
      out.write("					aconfirm += \"");
      out.print(uList.get(0).getMnum());
      out.write("\" + \",\";					\r\n");
      out.write("				}else{\r\n");
      out.write("					aconfirm += cValCk + \",\";	\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$('#aconfirm').val(aconfirm);\r\n");
      out.write("\r\n");
      out.write("			$('#alevel').val('09');	\r\n");
      out.write("			\r\n");
      out.write("			$('#sangsinForm').attr({\r\n");
      out.write("				'action':'/tr_spring/appPassUpdate.tr',    \r\n");
      out.write("				'method':'POST',\r\n");
      out.write("				'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("			}).submit();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on(\"click\", '#reject', function(){\r\n");
      out.write("	         $('#sangsinForm').attr({\r\n");
      out.write("	            \"action\":\"/tr_spring/appRejectUpdate.tr\",\r\n");
      out.write("	            \"method\":\"POST\",\r\n");
      out.write("	            \"enctype\":\"application/x-www-form-urlencoded\"\r\n");
      out.write("	         }).submit();\r\n");
      out.write("	         \r\n");
      out.write("	      });\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		function frequency(str){\r\n");
      out.write("			var nCnt = 0;\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < str.length; i++) {\r\n");
      out.write("				var at = str.charAt(i);\r\n");
      out.write("				\r\n");
      out.write("				if (at === '@') {\r\n");
      out.write("					nCnt++;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			return nCnt;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"GET\",\r\n");
      out.write("			url: '/tr_spring/appAlert.tr',\r\n");
      out.write("			success : function(result){\r\n");
      out.write("				\r\n");
      out.write("				if (result == 'ALERT_YES') {\r\n");
      out.write("					$('#bell').attr(\"src\", \"/tr_spring/resources/images/alert.png\")\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xtr, status, error){\r\n");
      out.write("				alert(xtr + \":\" + status + \":\" + error);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-dark sticky-top\" style=\"background-color: #C5E0B4;padding-right:0;\">\r\n");
      out.write("		<!--LOGO-->\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"/tr_spring/mainPage.tr\" >&nbsp&nbsp<img src=\"../resources/images/logo-green2.png\" style=\"height:30px\"></a>\r\n");
      out.write("		<!--Links-->\r\n");
      out.write("		<div class=\"container-fluid full-width\">\r\n");
      out.write("		<ul class=\"nav navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a class=\"nav-link dropdown-toggle\" id=\"dropdown01\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"padding-top:13px;font-size:18px;color:#534825;font-weight:bold;cursor:pointer\">전자결재</a>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/mainPage.tr\">메인페이지</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tBoardSelectAll.tr\">게시판</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tMemAddrBook.tr\">주소록</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/appSelect/A.tr\">전자결재</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"#\">일정</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/trWorkForm.tr\">인사</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div>\r\n");
      out.write("						<div class=\"dropdown\" style=\"position:absolute;right:80px\">\r\n");
      out.write("				<img id=\"bell\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\" src=\"/tr_spring/resources/images/notification-bell.png\" alt=\"\" width=\"32\" height=\"32\" style=\"cursor:pointer\">\r\n");
      out.write("			</div>\r\n");
      out.write("		<div>\r\n");
      out.write("		<div class=\"dropdown\" style=\"left:-10px;cursor:pointer\">\r\n");
      out.write("			<a href=\"#\" class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle dropdown-toggle-no-caret\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			  <img src=\"../fileupload/tmem/");
      out.print( mvo.getMphoto() );
      out.write("\" alt=\"\" width=\"35\" height=\"35\" class=\"rounded-circle me-2\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\" style=\"left:-110px\" aria-labelledby=\"dropdownUser1\">\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"#\">마이 페이지</a></li>\r\n");
      out.write("			  <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"../terraLogout.tr\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("		<div class=\"row\" style=\"margin-right: 0;\">\r\n");
      out.write("		  <div class=\"col-3\" >\r\n");
      out.write("			<!-- 사이드바 내용 -->\r\n");
      out.write("			<div class=\"sidebar\">\r\n");
      out.write("			  <!-- 사이드바 내용을 추가 -->\r\n");
      out.write("			  <div class=\"d-flex flex-column flex-shrink-0 p-3 \" style=\"width: 280px; height:auto; overflow-y: auto; height: 100vh;position:fixed; background-color:#E2F0D9;\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary\" id=\"istBtn\" style=\"background-color:#92D050;height:50px;border:0; font-size:20px;font-weight:1000;color:#534825;cursor:pointer\">+ 작성하기</button>\r\n");
      out.write("				<br>\r\n");
      out.write("				<ul class=\"list-unstyled ps-0\">\r\n");
      out.write("					<li class=\"mb-1\">\r\n");
      out.write("					  <button class=\"btn btn-toggle align-items-center rounded collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#home-collapse\" aria-expanded=\"true\" style=\"font-size: 20px;cursor:pointer\">\r\n");
      out.write("						진행중인 문서\r\n");
      out.write("					  </button>\r\n");
      out.write("					  <div class=\"collapse show\" id=\"home-collapse\">\r\n");
      out.write("						<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/A.tr'\"><img src=\"/tr_spring/resources/images/file.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">전체</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\"><img src=\"/tr_spring/resources/images/hourglass.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">대기</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/P.tr'\"><img src=\"/tr_spring/resources/images/time.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">예정</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/K.tr'\"><img src=\"/tr_spring/resources/images/loading.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">진행</span></div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"mb-1\">\r\n");
      out.write("					  <button class=\"btn btn-toggle align-items-center rounded collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#dashboard-collapse\" aria-expanded=\"true\" style=\"font-size: 20px;cursor:pointer\">\r\n");
      out.write("						문서함\r\n");
      out.write("					  </button>\r\n");
      out.write("					  <div class=\"collapse show\" id=\"dashboard-collapse\">\r\n");
      out.write("						<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/AllDoc.tr'\"><img src=\"/tr_spring/resources/images/file.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">전체</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/D.tr'\"><img src=\"/tr_spring/resources/images/pencil.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">기안</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/AA.tr'\"><img src=\"/tr_spring/resources/images/digital-signature.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">결재</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/R.tr'\"><img src=\"/tr_spring/resources/images/add-user.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">참조</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/RJ.tr'\"><img src=\"/tr_spring/resources/images/traffic-signal.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">반려</span></div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</li>\r\n");
      out.write("				  </ul>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		  <div class=\"col-9\" style=\"left:400px;top:30px\">\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("			  <!-- 본문 내용을 추가 -->\r\n");
      out.write("<form id=\"sangsinForm\">\r\n");
      out.write("<div style=\"display: flex;\" id=\"btnshow\">\r\n");
      out.write("	<span id=\"reject\" style=\"color:green;cursor:pointer;\">반려</span>&nbsp;&nbsp;\r\n");
      out.write("	<span id=\"passY\" style=\"display:none;color:green;cursor:pointer;\">전결</span>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"mpo\">문서 종류</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;기안서</td>\r\n");
      out.write("		<td class=\"mpo\">문서 번호</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(advo.getAnum() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"mpo\">기안 부서</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(CodeUtil.dappVal(advo.getMdeptno()));
      out.write("</td>\r\n");
      out.write("		<td class=\"mpo\">기안자</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(advo.getMname());
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"mpo\">보존 연한</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(advo.getDeletedate());
      out.write(" 년</td>\r\n");
      out.write("		<td class=\"mpo\">보안 등급</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(CodeUtil.aauthVal(advo.getAauth()));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"mpo\">기안 일시</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(advo.getInsertdate());
      out.write("</td>\r\n");
      out.write("		<td class=\"mpo\">완료 일시</td>\r\n");
      out.write("		<td colspan=\"2\">&nbsp;");
      out.print(advo.getFindate());
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td rowspan=\"3\" class=\"mpo\">결재</td>\r\n");
      out.write("		");
 for (int i = 0; i < 5; i++) { 
      out.write("\r\n");
      out.write("		<td class=\"mpo\">\r\n");
      out.write("			");
 if (i < aList.size()) { 
      out.write("\r\n");
      out.write("				");
      out.print( CodeUtil.mpositionVal(aList.get(i).getMposition()) );
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		");
if(pList != null && pList.size() > 0){ 
      out.write("\r\n");
      out.write("		");
 for (int i = 0; i < 5; i++) { 
      out.write("\r\n");
      out.write("		<td style=\"text-align:center;\">\r\n");
      out.write("			");
if(confirm[i].equals("~")) {
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/pass.png\"/>\r\n");
      out.write("			");
}else if(confirm[i].equals("@")) {
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/traffic-signal.png\"/>\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"@\"/>\r\n");
      out.write("			");
}else if (confirm[i].equals(app[i])) { 
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/evaluate.png\"/>\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"");
      out.print(app[i]);
      out.write("\"/>\r\n");
      out.write("			");
}else if(app[i].equals(uList.get(0).getMnum())|| app[i].equals(pList.get(0).getMnum()) && !advo.getAlevel().equals("00")){ 
      out.write("\r\n");
      out.write("				<input type=\"button\" value=\"대결\" name=\"approvalproxy\" id=\"approvalproxy\" style=\"cursor:pointer;\"/>  \r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"");
      out.print(uList.get(0).getMnum());
      out.write("\"/>\r\n");
      out.write("			");
}else if(i < f || i < j){ 
      out.write("\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"@\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		");
 }}}else{
      out.write("\r\n");
      out.write("		");
 for (int i = 0; i < 5; i++) { 
      out.write("\r\n");
      out.write("		<td style=\"text-align:center;\">\r\n");
      out.write("			");
if(confirm[i].equals("~")) {
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/pass.png\"/>\r\n");
      out.write("			");
}else if(confirm[i].equals("@")) {
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/traffic-signal.png\"/>\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"@\"/>\r\n");
      out.write("			");
}else if (confirm[i].equals(app[i])) { 
      out.write("\r\n");
      out.write("				<img style=\"width:50px;height:50px;\" src=\"../resources/images/evaluate.png\"/>\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"");
      out.print(app[i]);
      out.write("\"/>\r\n");
      out.write("			");
}else if(app[i].equals(uList.get(0).getMnum()) && !advo.getAlevel().equals("00")){ 
      out.write("\r\n");
      out.write("				<input type=\"button\" value=\"결재\" name=\"approval\" id=\"approval\"style=\"cursor:pointer;\"/>\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"");
      out.print(uList.get(0).getMnum());
      out.write("\"/>\r\n");
      out.write("			");
}else if(i < f || i < j){ 
      out.write("\r\n");
      out.write("				<input type=\"hidden\" class=\"confirms\" value=\"@\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		");
 }}} 
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		");
 for (int i = 0; i < 5; i++) { 
      out.write("\r\n");
      out.write("		<td style=\"text-align:center\">\r\n");
      out.write("			");
 if (i < aList.size()) { 
      out.write("\r\n");
      out.write("				");
      out.print( aList.get(i).getMname() );
      out.write("\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"mpo\">참조</td>\r\n");
      out.write("		<td colspan=\"5\">");
      out.print(ref);
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div style=\"width:780px\"><h2>");
      out.print(advo.getDsubject());
      out.write("</h2>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<p>");
      out.print(advo.getDmemo());
      out.write("</p></div>\r\n");
      out.write("	<input type=\"hidden\" id=\"alevel\" name=\"alevel\"/>\r\n");
      out.write("	<input type=\"hidden\" id=\"aconfirm\" name=\"aconfirm\"/>\r\n");
      out.write("	<input type=\"hidden\" id=\"aapp\" name=\"aapp\" value=\"");
      out.print(advo.getAapp());
      out.write("\"/>\r\n");
      out.write("	<input type=\"hidden\" id=\"anum\" name=\"anum\" value=\"");
      out.print(advo.getAnum());
      out.write("\"/>\r\n");
      out.write("	<input type=\"hidden\" id=\"atype\" name=\"atype\" value=\"");
      out.print(advo.getAtype());
      out.write("\"/>\r\n");
      out.write("</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"../resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
