/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-27 08:52:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraApproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kos.tr.member.vo.TerraMemberVO;
import java.util.ArrayList;
import com.kos.tr.common.CodeUtil;

public final class modal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kos.tr.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	Object obj = request.getAttribute("aList");
	ArrayList<TerraMemberVO> aList = (ArrayList<TerraMemberVO>) obj;


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table{\r\n");
      out.write("		border:solid 1px black;\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		\r\n");
      out.write("		padding:0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	ul {\r\n");
      out.write("    	list-style: none; /* 점(불릿)을 없애는 스타일 설정 */\r\n");
      out.write("  	}\r\n");
      out.write("	.c1{\r\n");
      out.write(" 		width:200px; \r\n");
      out.write("		height:50px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.emp{\r\n");
      out.write("		display:none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.modal {\r\n");
      out.write("	  display: none;\r\n");
      out.write("	  position: fixed;\r\n");
      out.write("	  z-index: 1;\r\n");
      out.write("	  left: 0;\r\n");
      out.write("	  top: 0;\r\n");
      out.write("	  width: 100%;\r\n");
      out.write("	  height: 100%;\r\n");
      out.write("	  overflow: auto;\r\n");
      out.write("	  background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.modal-content {\r\n");
      out.write("	  background-color: #fefefe;\r\n");
      out.write("	  margin: 15% auto;\r\n");
      out.write("	  padding: 20px;\r\n");
      out.write("	  border: 1px solid #888;\r\n");
      out.write("	  width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.close {\r\n");
      out.write("	  float: right;\r\n");
      out.write("	  font-size: 28px;\r\n");
      out.write("	  font-weight: bold;\r\n");
      out.write("	  cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.close:hover {\r\n");
      out.write("	  color: #000;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dep{\r\n");
      out.write("		color:green;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.dep', function(){\r\n");
      out.write("			var dep = $(this).val()\r\n");
      out.write("			\r\n");
      out.write("			$('.emp').css('display', 'none');\r\n");
      out.write("			$('.' + dep).css('display','block');\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.plusBtn', function(){\r\n");
      out.write("			\r\n");
      out.write("			var plusId = $(this).attr(\"id\");\r\n");
      out.write("			var empName = $(\"#empList option:selected\").html();\r\n");
      out.write("			\r\n");
      out.write("			var nameOption = $(\"<option value=\" + $(\"#empList option:selected\").val() + \">\");\r\n");
      out.write("			nameOption.html(empName + \" \");\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			if (plusId == 'plus1') {\r\n");
      out.write("				nameOption.addClass(\"selected1\");\r\n");
      out.write("				$(\"#appList\").append(nameOption);	\r\n");
      out.write("				\r\n");
      out.write("			}else if(plusId == 'plus2'){\r\n");
      out.write("				nameOption.addClass(\"selected2\");\r\n");
      out.write("				$(\"#refList\").append(nameOption);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.minBtn', function(){\r\n");
      out.write("					\r\n");
      out.write("			var minId = $(this).attr(\"id\");\r\n");
      out.write("			\r\n");
      out.write("			if (minId == 'min1') {\r\n");
      out.write("				$(\"#appList option:selected\").remove();\r\n");
      out.write("			}else if(minId == 'min2'){\r\n");
      out.write("				$(\"#refList option:selected\").remove();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#openModal\").click(function() {\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"block\");\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 모달 닫기 버튼 클릭 이벤트 처리\r\n");
      out.write("		$(document).on('click', '#cfmBtn', function(){\r\n");
      out.write("			\r\n");
      out.write("			var aapp = \"\";\r\n");
      out.write("			var aref = \"\";\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < 5; i++) {\r\n");
      out.write("				$('#r'+ (i+1)).text($('#appList').text().split(' ')[(i*2)]);\r\n");
      out.write("				$('#n'+ (i+1)).text($('#appList').text().split(' ')[(i*2)+1]);\r\n");
      out.write("				$('#areftext').text($('#refList').text());\r\n");
      out.write("				if ($('#appList').find('.selected1:nth-child('+ (i+1) +')').val() === undefined) {\r\n");
      out.write("					aapp += \"-,\";\r\n");
      out.write("				}else{\r\n");
      out.write("					aapp += $('#appList').find('.selected1:nth-child('+ (i+1) +')').val() + ',';	\r\n");
      out.write("				}\r\n");
      out.write("				if ($('#refList').find('.selected2:nth-child('+ (i+1) +')').val() === undefined) {\r\n");
      out.write("					aref += \"-,\";\r\n");
      out.write("				}else{\r\n");
      out.write("					aref += $('#refList').find('.selected2:nth-child('+ (i+1) +')').val() + ',';					\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			$('#aapp').val(aapp);\r\n");
      out.write("			$('#aref').val(aref);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			console.log(aapp);\r\n");
      out.write("			console.log(aref);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"none\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.closed', function(){\r\n");
      out.write("			\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"none\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		// 모달 외부 클릭 이벤트 처리\r\n");
      out.write("		$(document).click(function(event) {\r\n");
      out.write("			if ($(event.target).is(\"#myModal\")) {\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"none\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=openModal style=\"width:100px;height:15px;\"><span style=\"color:green\">결재선 설정</span></div>\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\" style=\"align:center;width:1050px\">\r\n");
      out.write("    <span class=\"close closed\" style=\"text-align:right\">&times;</span>\r\n");
      out.write("    <h4 style=\"color:green\">결재선 설정</h4>\r\n");
      out.write("    <table>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"6\" style=\"width:150px;height:446px;\">\r\n");
      out.write("	<ul id=\"folderList\" style=\"text-align:center\">\r\n");
      out.write("      <li class=\"dep\" value=\"1000\">관리부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"2000\">기획부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"3000\">영업부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"4000\">생산부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"5000\">안전관리부</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"6\" style=\"width:100px;height:400px;text-align:center\">\r\n");
      out.write("		<select name=\"empList\" id=\"empList\" multiple=\"multiple\" style=\"width:228px;height:500px;\">\r\n");
      out.write("			");

				for(int i=0; i < aList.size(); i++){
					TerraMemberVO tmvo = aList.get(i);
			
      out.write("\r\n");
      out.write("			<option class=\"");
      out.print(tmvo.getMdeptno());
      out.write(" emp\" value=\"");
      out.print(tmvo.getMnum());
      out.write('"');
      out.write('>');
      out.print(tmvo.getMname());
      out.write(' ');
      out.print(CodeUtil.mpositionVal(tmvo.getMposition()));
      out.write("</option>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"3\" style=\"width:20px\"><input type=\"button\" class=\"plusBtn\" id=\"plus1\" value=\">\"/><br>\r\n");
      out.write("	<input type=\"button\" class=\"minBtn\" id=\"min1\" value=\"<\"/></td>\r\n");
      out.write("	<td class=\"c1\" style=\"text-align:center;width:200px;font-weight:bold;\">결재</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"2\" style=\"text-align:center\"><select name=\"appList\" id=\"appList\" multiple=\"multiple\" style=\"width:228px;height:223px;\"></select></td>\r\n");
      out.write("</tr >\r\n");
      out.write("<tr>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"3\" style=\"width:20px\"><input type=\"button\" class=\"plusBtn\" id=\"plus2\" value=\">\"/><br><input type=\"button\" class=\"minBtn\" id=\"min2\" value=\"<\"/></td>\r\n");
      out.write("	<td class=\"c1\" style=\"text-align:center;width:200px;font-weight:bold;\">참조</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"c1\" rowspan=\"2\" style=\"text-align:center\"><select name=\"refList\" id=\"refList\" multiple=\"multiple\" style=\"width:228px;height:223px;\"></select></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<div style=\"text-align:center\">\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" style=\"background-color:#92D050;border-color:#92D050;width:100px\" id=\"cfmBtn\">확인</button>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-light closed\" style=\"border-color:#92D050;width:100px\">취소</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
