/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-03 08:54:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraApproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import com.kos.tr.common.CodeUtil;
import com.kos.tr.app.vo.AppDocVO;
import com.kos.tr.member.vo.TerraMemberVO;

public final class trVacationForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kos.tr.app.vo.AppDocVO");
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kos.tr.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

		Object obj = request.getAttribute("aList");
		
		List<TerraMemberVO> list = (List<TerraMemberVO>)obj;
				
		Object sbj = request.getAttribute("uList");
		List<TerraMemberVO> ulist = (List<TerraMemberVO>)sbj;
		
		TerraMemberVO ttmvo = ulist.get(0);
		
		
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("			 <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("			 <link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  			 <script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("  			 <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maxinum-scale=1, user-scalable=no\">\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\">\r\n");
      out.write("			<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js\"></script>\r\n");
      out.write("			<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("			<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/sidebars.css\">\r\n");
      out.write("			<link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/sidebars/\">\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("		.icon_img{\r\n");
      out.write("		\r\n");
      out.write("			width:22px;\r\n");
      out.write("			height: 22px;\r\n");
      out.write("			margin-bottom: 10px;\r\n");
      out.write("			margin-left: 25px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.dropdown-toggle-no-caret::after {\r\n");
      out.write("			display: none;\r\n");
      out.write("		}		\r\n");
      out.write("		.initial-size {\r\n");
      out.write("		  	min-height: 200px; \r\n");
      out.write("		  	width : 1000px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		table {\r\n");
      out.write("			border-collapse : collapse;\r\n");
      out.write("			width:1000px;\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("		.a {\r\n");
      out.write("			width: flex;\r\n");
      out.write("			height:100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.rank{\r\n");
      out.write("			width:flex;\r\n");
      out.write("			height: 40px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.aauto {\r\n");
      out.write("			width: flex;\r\n");
      out.write("			height:100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.mposition{\r\n");
      out.write("			width: 173px;\r\n");
      out.write("			height:40px;\r\n");
      out.write("			text-align:center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.idx{\r\n");
      out.write("			cursor:pointer;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.texttp{\r\n");
      out.write("			text-align:center;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				$(document).on('click', '#istBtn', function(){\r\n");
      out.write("					location.href = \"../appInsertDoc.tr\";\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				$(document).on('mouseenter', '.idx', function(){\r\n");
      out.write("\r\n");
      out.write("					$(this).css('background-color', '#ecf9ec');\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				$(document).on('mouseleave', '.idx', function(){\r\n");
      out.write("\r\n");
      out.write("					$(this).css('background-color', '#E2F0D9');\r\n");
      out.write("					});\r\n");
      out.write("				\r\n");
      out.write("				$(document).on('mouseleave', '#nowSelected', function(){\r\n");
      out.write("\r\n");
      out.write("					$(this).css('background-color', '#C5E0B4');\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				// 결재라인 서명\r\n");
      out.write("				$(document).on(\"click\", \"#rBtn\", function() {\r\n");
      out.write("					\r\n");
      out.write("					var rank1 = $(\"#rank1\").val();\r\n");
      out.write("					$(\"#r1\").text(rank1);\r\n");
      out.write("									\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				// 결재라인 도장 ---- 수정필요함\r\n");
      out.write("				$(document).on(\"click\", \"#aBtn\", function() {\r\n");
      out.write("					var auto1 = $(\"#auto\").val();\r\n");
      out.write("					 // $(\"#a1\").get(auto1);\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("				// 기안하기 \r\n");
      out.write("				$(document).on(\"click\", \"#alevel01\", function() {\r\n");
      out.write("					\r\n");
      out.write("					var a = $('.ql-editor').html();\r\n");
      out.write("		            \r\n");
      out.write("		            var b =$(\"#vmemo\").val(a);\r\n");
      out.write("					\r\n");
      out.write("					$('#alevel').val(\"01\");\r\n");
      out.write("					\r\n");
      out.write("					$('#vacApprovalForm').attr({\r\n");
      out.write("						'action':'../appInsert/V.tr',\r\n");
      out.write("						'method':'POST',\r\n");
      out.write("						'enctype':'multipart/form-data'\r\n");
      out.write("					}).submit();\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				// 휴가날짜 계산하기\r\n");
      out.write("				$(\"#enddate\").change(function() {\r\n");
      out.write("					\r\n");
      out.write("					let startdate = document.querySelector(\"#startdate\").value;\r\n");
      out.write("					let enddate = document.querySelector(\"#enddate\").value;\r\n");
      out.write("					\r\n");
      out.write("					startdate = new Date(startdate); \r\n");
      out.write("					enddate = new Date(enddate);  \r\n");
      out.write("					\r\n");
      out.write("					if (enddate <= startdate) {\r\n");
      out.write("						alert(\"휴가종료일을 확인해주세요\");\r\n");
      out.write("						$(\"#enddate\").val(\"\");\r\n");
      out.write("					\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					var weekdayCount = getWeekdayCount(startdate, enddate);\r\n");
      out.write("					console.log(weekdayCount);  \r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					$(\"#mholiday\").val(Number(\"15\")-weekdayCount);\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				function getWeekdayCount(startdate, enddate) {\r\n");
      out.write("				\r\n");
      out.write("					  var count = 0;\r\n");
      out.write("					  var currentDate = new Date(startdate);\r\n");
      out.write("					\r\n");
      out.write("					  // endDate까지 반복하면서 주말(토요일과 일요일)을 제외한 평일 수를 계산합니다.\r\n");
      out.write("					  while (currentDate <= enddate) {\r\n");
      out.write("					    var dayOfWeek = currentDate.getDay();\r\n");
      out.write("					    if (dayOfWeek !== 0 && dayOfWeek !== 6) {\r\n");
      out.write("					      count++;\r\n");
      out.write("					    }\r\n");
      out.write("					    currentDate.setDate(currentDate.getDate() + 1);\r\n");
      out.write("					  }\r\n");
      out.write("					\r\n");
      out.write("					  return count;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$('.ql-toolbar').css('width',\"1000px\");\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:\"GET\",\r\n");
      out.write("					url: '/tr_spring/appAlert.tr',\r\n");
      out.write("					success : function(result){\r\n");
      out.write("						\r\n");
      out.write("						if (result == 'ALERT_YES') {\r\n");
      out.write("							$('#bell').attr(\"src\", \"/tr_spring/resources/images/alert.png\")\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error: function(xtr, status, error){\r\n");
      out.write("						alert(xtr + \":\" + status + \":\" + error);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm navbar-dark sticky-top\" style=\"background-color: #C5E0B4;padding-right:0;\">\r\n");
      out.write("		<!--LOGO-->\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"/tr_spring/mainPage.tr\" >&nbsp&nbsp<img src=\"../resources/images/logo-green2.png\" style=\"height:30px\"></a>\r\n");
      out.write("		<!--Links-->\r\n");
      out.write("		<div class=\"container-fluid full-width\">\r\n");
      out.write("		<ul class=\"nav navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a class=\"nav-link dropdown-toggle\" id=\"dropdown01\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"padding-top:13px;font-size:18px;color:#534825;font-weight:bold;cursor:pointer\">전자결재</a>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/mainPage.tr\">메인페이지</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tBoardSelectAll.tr\">게시판</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/tMemAddrBook.tr\">주소록</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/appSelect/A.tr\">전자결재</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"#\">일정</a></li>\r\n");
      out.write("				  <li><a class=\"dropdown-item\" href=\"/tr_spring/trWorkForm.tr\">인사</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div>\r\n");
      out.write("						<div class=\"dropdown\" style=\"position:absolute;right:80px\">\r\n");
      out.write("				<img id=\"bell\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\" src=\"/tr_spring/resources/images/notification-bell.png\" alt=\"\" width=\"32\" height=\"32\" style=\"cursor:pointer\">\r\n");
      out.write("			</div>\r\n");
      out.write("		<div>\r\n");
      out.write("		<div class=\"dropdown\" style=\"left:-10px;cursor:pointer\">\r\n");
      out.write("			<a href=\"#\" class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle dropdown-toggle-no-caret\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			  <img src=\"../fileupload/tmem/");
      out.print( ttmvo.getMphoto() );
      out.write("\" alt=\"\" width=\"35\" height=\"35\" class=\"rounded-circle me-2\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\" style=\"left:-110px\" aria-labelledby=\"dropdownUser1\">\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"#\">마이 페이지</a></li>\r\n");
      out.write("			  <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("			  <li><a class=\"dropdown-item\" href=\"../terraLogout.tr\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("		<div class=\"row\" style=\"margin-right: 0;\">\r\n");
      out.write("		  <div class=\"col-3\" >\r\n");
      out.write("			<!-- 사이드바 내용 -->\r\n");
      out.write("			<div class=\"sidebar\">\r\n");
      out.write("			  <!-- 사이드바 내용을 추가 -->\r\n");
      out.write("			  <div class=\"d-flex flex-column flex-shrink-0 p-3 \" style=\"width: 280px; height:auto; overflow-y: auto; height: 100vh;position:fixed; background-color:#E2F0D9;\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary\" id=\"istBtn\" style=\"background-color:#92D050;height:50px;border:0; font-size:20px;font-weight:1000;color:#534825;cursor:pointer\">+ 작성하기</button>\r\n");
      out.write("				<br>\r\n");
      out.write("				<ul class=\"list-unstyled ps-0\">\r\n");
      out.write("					<li class=\"mb-1\">\r\n");
      out.write("					  <button class=\"btn btn-toggle align-items-center rounded collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#home-collapse\" aria-expanded=\"true\" style=\"font-size: 20px;cursor:pointer\">\r\n");
      out.write("						진행중인 문서\r\n");
      out.write("					  </button>\r\n");
      out.write("					  <div class=\"collapse show\" id=\"home-collapse\">\r\n");
      out.write("						<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/A.tr'\"><img src=\"/tr_spring/resources/images/file.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">전체</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/W.tr'\"><img src=\"/tr_spring/resources/images/hourglass.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">대기</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/P.tr'\"><img src=\"/tr_spring/resources/images/time.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">예정</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/K.tr'\"><img src=\"/tr_spring/resources/images/loading.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">진행</span></div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"mb-1\">\r\n");
      out.write("					  <button class=\"btn btn-toggle align-items-center rounded collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#dashboard-collapse\" aria-expanded=\"true\" style=\"font-size: 20px;cursor:pointer\">\r\n");
      out.write("						문서함\r\n");
      out.write("					  </button>\r\n");
      out.write("					  <div class=\"collapse show\" id=\"dashboard-collapse\">\r\n");
      out.write("						<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/AllDoc.tr'\"><img src=\"/tr_spring/resources/images/file.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">전체</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/D.tr'\"><img src=\"/tr_spring/resources/images/pencil.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">기안</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/AA.tr'\"><img src=\"/tr_spring/resources/images/digital-signature.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">결재</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/R.tr'\"><img src=\"/tr_spring/resources/images/add-user.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">참조</span></div></li>\r\n");
      out.write("						  <li><div class=\"idx\" onclick=\"javascript:location.href='/tr_spring/appSelect/RJ.tr'\"><img src=\"/tr_spring/resources/images/traffic-signal.png\" class=\"icon_img\"><span class=\"link-dark rounded\" style=\"font-size:20px;margin-left:12px\">반려</span></div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</li>\r\n");
      out.write("				  </ul>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		  <div class=\"col-9\" style=\"left:400px;top:30px\">\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("			  <!-- 본문 내용을 추가 -->\r\n");
      out.write("		<form name=\"vacApprovalForm\" id=\"vacApprovalForm\">\r\n");
      out.write("		<p id=\"alevel01\" style=\"color:green\">기안하기</p>\r\n");
      out.write("	<table border=\"1\" class=\"type\" name=\"type\" id=\"type\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"1\">\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\" height=\"40px;\"class=\"texttp\">문서 종류</th>\r\n");
      out.write("			<td><input type=\"hidden\" id=\"anum\" name=\"anum\" readonly>&nbsp;휴가신청서</td>\r\n");
      out.write("			<th width=\"130px;\" height=\"40px;\"class=\"texttp\">작성자</th>\r\n");
      out.write("			<td><input type=\"hidden\"  id=\"mnum\" name=\"mnum\" readonly>&nbsp;");
      out.print( ttmvo.getMname() );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\"  height=\"40px;\"class=\"texttp\">보존연한</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			&nbsp;<select id=\"deletedate\" name=\"deletedate\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"deletedate1\" selected>보존연한</option>\r\n");
      out.write("				<option value=\"1\">1</option>\r\n");
      out.write("				<option value=\"3\">3</option>\r\n");
      out.write("				<option value=\"5\">5</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			년</td>\r\n");
      out.write("			<th width=\"130px;\"  height=\"40px;\"class=\"texttp\">보안등급</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			&nbsp;<select id=\"aauth\" name=\"aauth\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"aauth1\" selected>보안등급</option>\r\n");
      out.write("				<option value=\"09\">S</option>\r\n");
      out.write("				<option value=\"04\">A</option>\r\n");
      out.write("				<option value=\"03\">B</option>\r\n");
      out.write("				<option value=\"01\">C</option>\r\n");
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "modal.jsp", out, false);
      out.write("<br></div>\r\n");
      out.write("	<table border=\"1\" class=\"vac_sign\" name=\"vac_sign\" id=\"vac_sign\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"5\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th rowspan=\"3\" width=\"130px;\"class=\"texttp\">신청</th>\r\n");
      out.write("			<td class=\"mposition\" id=\"n1\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"n2\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"n3\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"n4\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"n5\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"aauto\">\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"rank\">\r\n");
      out.write("			<td class=\"mposition\" id=\"r1\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"r2\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"r3\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"r4\"></td>\r\n");
      out.write("			<td class=\"mposition\" id=\"r5\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\"class=\"texttp\">참조</th>\r\n");
      out.write("			<td colspan=\"6\" style=\"height:50px;\" name=\"areftext\" id=\"areftext\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\" style=\"background-color: #E2F0D9\"class=\"texttp\">잔여휴가</th>\r\n");
      out.write("			<td><input type=\"text\" name=\"mholiday\" id=\"mholiday\" style=\" width: 20px; outline:none; border:none;border-right:0px; border-top:0px; boder-left:0px; boder-bottom:0px;\" value=\"");
      out.print(ttmvo.getMholiday() );
      out.write("\" readonly>일</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div>\r\n");
      out.write("\r\n");
      out.write("		<table border=\"1\" class=\"vac_start\" name=\"vac_start\" id=\"vac_start\"> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<th id=\"start_end\" width=\"130px;\" style=\"background-color: #E2F0D9\"class=\"texttp\">휴가시작일</th>	\r\n");
      out.write("				<td>&nbsp;<input type=\"date\" id=\"startdate\" name=\"startdate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th id=\"start_end\" width=\"130px;\" style=\"background-color: #E2F0D9\"class=\"texttp\">휴가종료일</th>\r\n");
      out.write("				<td>&nbsp;<input type=\"date\" id=\"enddate\" name=\"enddate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		<table border=\"1\" class=\"vac_user\" name=\"vac_user\" id=\"vac_user\">\r\n");
      out.write("			<tr>\r\n");
      out.write("			<th width=\"130px;\" style=\"background-color: #E2F0D9\"class=\"texttp\">제목</th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" id=\"vsubject\" name=\"vsubject\" style=\"width:95%; outline:none; border:none;border-right:0px; border-top:0px; boder-left:0px; boder-bottom:0px;\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>	\r\n");
      out.write("	</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("		<div id=\"editor\" class=\"initial-size\"></div>	\r\n");
      out.write("	    <script>\r\n");
      out.write("			\r\n");
      out.write("	  		var quill = new Quill('#editor', {\r\n");
      out.write("	    	  // Quill 설정 옵션\r\n");
      out.write("	    	});\r\n");
      out.write("	\r\n");
      out.write("	    	// 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("	    	var editorContainer = document.querySelector('#editor');\r\n");
      out.write("	    	editorContainer.addEventListener('click', function() {\r\n");
      out.write("	    	  quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("	    	});\r\n");
      out.write("	    \r\n");
      out.write("	        var toolbarOptions = [\r\n");
      out.write("	            ['bold', 'italic', 'underline', 'strike'],\r\n");
      out.write("	            ['link', 'image'],\r\n");
      out.write("	            [{ 'list': 'ordered' }, { 'list': 'bullet' }],\r\n");
      out.write("	            [{ 'header': [1, 2] }]\r\n");
      out.write("	        ];\r\n");
      out.write("			\r\n");
      out.write("	        var quill = new Quill('#editor', {\r\n");
      out.write("	            modules: {\r\n");
      out.write("	                toolbar: toolbarOptions\r\n");
      out.write("	            },\r\n");
      out.write("	            theme: 'snow'\r\n");
      out.write("	        });\r\n");
      out.write("	        \r\n");
      out.write("	        function myFunction(){\r\n");
      out.write("	        \r\n");
      out.write("	        }\r\n");
      out.write("	        \r\n");
      out.write("    </script>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table border=\"1\" class=\"type\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\" style=\"background-color: #E2F0D9\" class=\"texttp\">첨부파일</th>\r\n");
      out.write("			<td>&nbsp;<input type=\"file\" id=\"vfile\" name=\"vfile\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<input type=\"hidden\" name=\"aref\" id=\"aref\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"aapp\" id=\"aapp\" value=\"\">\r\n");
      out.write("	<input type=\"hidden\" name=\"atype\" id=\"atype\" value=\"V\">\r\n");
      out.write("	<input type=\"hidden\" id=\"vmemo\" name=\"vmemo\">\r\n");
      out.write("	<input type=\"hidden\" name=\"alevel\" id=\"alevel\">\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"../resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
