/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-14 03:43:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.terraApproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kos.tr.member.vo.TerraMemberVO;
import java.util.ArrayList;

public final class trVacation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/terraApproval/modal.jsp", Long.valueOf(1689207874012L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kos.tr.member.vo.TerraMemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/kosSpring/calendar_datepicker/jquery-ui-1.12.1/jquery-ui.min.css\">\r\n");
      out.write("	<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  	<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("	\r\n");
      out.write("		// 결재라인 서명\r\n");
      out.write("		$(document).on(\"click\", \"#rBtn\", function() {\r\n");
      out.write("			\r\n");
      out.write("			var rank1 = $(\"#rank1\").val();\r\n");
      out.write("			alert(\"rank1 >>> \" + rank1);\r\n");
      out.write("			$(\"#r1\").text(rank1);\r\n");
      out.write("							\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 결재라인 도장 ---- 수정필요함\r\n");
      out.write("		$(document).on(\"click\", \"#aBtn\", function() {\r\n");
      out.write("			var auto1 = $(\"#auto\").val();\r\n");
      out.write("			alert(\"auto >>> \" + auto1);\r\n");
      out.write("			 // $(\"#a1\").get(auto1);\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		$(document).on(\"click\", \"#submit\", function() {\r\n");
      out.write("			alert(\"기안하기 >>>>> \");\r\n");
      out.write("			$(\"#vacApprovalForm\").attr({\r\n");
      out.write("				\"method\":\"GET\",\r\n");
      out.write("				\"action\":\"\"\r\n");
      out.write("				\r\n");
      out.write("			}).submit();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 휴가사용자 체크박스\r\n");
      out.write("		$(document).on(\"click\", \"#vac_check\", function() {\r\n");
      out.write("			\r\n");
      out.write("			if($(this).prop('checked')){\r\n");
      out.write("				$('.vac_check').prop('checked', false);\r\n");
      out.write("				$(this).prop('checked', true);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("				\r\n");
      out.write("		.initial-size {\r\n");
      out.write("		  	min-height: 200px; \r\n");
      out.write("		  	width : 1000px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		table {\r\n");
      out.write("			border-collapse : collapse;\r\n");
      out.write("			width:1000px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.a{\r\n");
      out.write("			width:100px;\r\n");
      out.write("			height:100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.rank {\r\n");
      out.write("			width:100px;\r\n");
      out.write("			height:40px;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		#vsubject{\r\n");
      out.write("			display : flex;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form name=\"vacApprovalForm\" id=\"vacApprovalForm\">\r\n");
      out.write("	\r\n");
      out.write("	<h2>휴가신청서</h2>\r\n");
      out.write("	<input type=\"hidden\" id=\"atype\" name=\"atype\" value=\"V\"> \r\n");
      out.write("	<table border=\"1\" class=\"type\" name=\"type\" id=\"type\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"1\">\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\">문서번호</th>\r\n");
      out.write("			<td><input type=\"text\" style=\"width:90%;\" id=\"anum\" name=\"anum\"></td>\r\n");
      out.write("			<th width=\"130px;\">작성자</th>\r\n");
      out.write("			<td><input type=\"text\" style=\"width:90%;\" id=\"mnum\" name=\"mnum\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"130px;\">보존연한</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			<select id=\"yearselect\" name=\"yearselect\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"y1\" selected>보존연한</option>\r\n");
      out.write("				<option value=\"1\">1</option>\r\n");
      out.write("				<option value=\"3\">3</option>\r\n");
      out.write("				<option value=\"5\">5</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			년</td>\r\n");
      out.write("			<th width=\"130px;\">보안등급</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			<select id=\"security\" name=\"security\" style=\"width:150px;\" >\r\n");
      out.write("				<option value=\"security1\" selected>보안등급</option>\r\n");
      out.write("				<option value=\"09\">S</option>\r\n");
      out.write("				<option value=\"05\">A</option>\r\n");
      out.write("				<option value=\"04\">B</option>\r\n");
      out.write("				<option value=\"01\">C</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table border=\"1\" class=\"vac_sign\" name=\"vac_sign\" id=\"vac_sign\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("			<col span=\"4\">\r\n");
      out.write("			<col span=\"1\" style=\"background-color: #E2F0D9\">\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th rowspan=\"3\">신청</th>\r\n");
      out.write("			<td id=\"r1\">1</td>\r\n");
      out.write("			<td id=\"r2\">2</td>\r\n");
      out.write("			<td id=\"r3\">3</td>\r\n");
      out.write("			<td id=\"r4\">4</td>\r\n");
      out.write("			<td id=\"r5\">5</td>	\r\n");
      out.write("			<td>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	Object obj = request.getAttribute("aList");
	ArrayList<TerraMemberVO> aList = (ArrayList<TerraMemberVO>) obj;


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table, tr, td{\r\n");
      out.write("		border:solid 1px black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	td{\r\n");
      out.write("		width:300px;\r\n");
      out.write("		height:100px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.emp{\r\n");
      out.write("		display:none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.modal {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("  background-color: #fefefe;\r\n");
      out.write("  margin: 15% auto;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  border: 1px solid #888;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close {\r\n");
      out.write("  float: right;\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover {\r\n");
      out.write("  color: #000;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.dep', function(){\r\n");
      out.write("			var dep = $(this).val()\r\n");
      out.write("			\r\n");
      out.write("			$('.emp').css('display', 'none');\r\n");
      out.write("			$('.' + dep).css('display','block');\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.plusBtn', function(){\r\n");
      out.write("			\r\n");
      out.write("			var plusId = $(this).attr(\"id\");\r\n");
      out.write("			var empName = $(\"#empList option:selected\").html();\r\n");
      out.write("			\r\n");
      out.write("			var nameOption = $(\"<option value=\" + $(\"#empList option:selected\").val() + \">\");\r\n");
      out.write("			nameOption.html(empName + \" \");\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			if (plusId == 'plus1') {\r\n");
      out.write("				nameOption.addClass(\"selected1\");\r\n");
      out.write("				$(\"#appList\").append(nameOption);	\r\n");
      out.write("				\r\n");
      out.write("			}else if(plusId == 'plus2'){\r\n");
      out.write("				nameOption.addClass(\"selected2\");\r\n");
      out.write("				$(\"#refList\").append(nameOption);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.minBtn', function(){\r\n");
      out.write("					\r\n");
      out.write("			var minId = $(this).attr(\"id\");\r\n");
      out.write("			\r\n");
      out.write("			if (minId == 'min1') {\r\n");
      out.write("				$(\"#appList option:selected\").remove();\r\n");
      out.write("			}else if(minId == 'min2'){\r\n");
      out.write("				$(\"#refList option:selected\").remove();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#openModal\").click(function() {\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"block\");\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 모달 닫기 버튼 클릭 이벤트 처리\r\n");
      out.write("		$(\".close\").click(function() {\r\n");
      out.write("			\r\n");
      out.write("			var aapp = \"\";\r\n");
      out.write("			var aref = \"\";\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < 5; i++) {\r\n");
      out.write("				aapp += $('#appList').find('.selected1:nth-child('+ (i+1) +')').val() + ',';\r\n");
      out.write("				aref += $('#refList').find('.selected2:nth-child('+ (i+1) +')').val() + ',';\r\n");
      out.write("				$('#n'+ (i+1)).text($('#appList').text().split(' ')[(i*2)]);\r\n");
      out.write("				$('#r'+ (i+1)).text($('#appList').text().split(' ')[(i*2)+1]);\r\n");
      out.write("				$('#aref').text($('#refList').text());\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			console.log(aapp);\r\n");
      out.write("			console.log(aref);\r\n");
      out.write("			\r\n");
      out.write("			$('#aapp').val(aapp);\r\n");
      out.write("			$('#aref').val(aref);\r\n");
      out.write("			\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"none\");\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 모달 외부 클릭 이벤트 처리\r\n");
      out.write("		$(document).click(function(event) {\r\n");
      out.write("			if ($(event.target).is(\"#myModal\")) {\r\n");
      out.write("			$(\"#myModal\").css(\"display\", \"none\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=openModal><span style=\"color:green\">결재선 설정</span></div>\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\">&times;</span>\r\n");
      out.write("    <h2>결재선 설정</h2>\r\n");
      out.write("    <table>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td rowspan=\"6\" style=\"width:228px;height:446px;\">\r\n");
      out.write("	<ul id=\"folderList\">\r\n");
      out.write("      <li class=\"dep\" value=\"1000\">관리부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"2000\">기획부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"3000\">영업부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"4000\">생산부</li>\r\n");
      out.write("      <li class=\"dep\" value=\"5000\">안전관리</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td rowspan=\"6\" style=\"width:228px;height:446px;\">\r\n");
      out.write("		<select name=\"empList\" id=\"empList\" multiple=\"multiple\" style=\"width:228px;height:446px;\">\r\n");
      out.write("			");

				for(int i=0; i < aList.size(); i++){
					TerraMemberVO tmvo = aList.get(i);
			
      out.write("\r\n");
      out.write("			<option class=\"");
      out.print(tmvo.getMdeptno());
      out.write(" emp\" value=\"");
      out.print(tmvo.getMnum());
      out.write('"');
      out.write('>');
      out.print(tmvo.getMname());
      out.write(' ');
      out.print(tmvo.getMposition() );
      out.write("</option>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td></td>\r\n");
      out.write("	<td>결재</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"button\" class=\"plusBtn\" id=\"plus1\" value=\">\"/></td>\r\n");
      out.write("	<td rowspan=\"2\"><select name=\"appList\" id=\"appList\" multiple=\"multiple\" style=\"width:228px;height:223px;\"></select></td>\r\n");
      out.write("</tr >\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"button\" class=\"minBtn\" id=\"min1\" value=\"<\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td></td>\r\n");
      out.write("	<td>참조</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"button\" class=\"plusBtn\" id=\"plus2\" value=\">\"/></td>\r\n");
      out.write("	<td rowspan=\"2\"><select name=\"refList\" id=\"refList\" multiple=\"multiple\" style=\"width:228px;height:223px;\"></select></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"button\" class=\"minBtn\" id=\"min2\" value=\"<\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"a\">\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"rank\">\r\n");
      out.write("			<td class=\"a\" id=\"n1\"></td>\r\n");
      out.write("			<td class=\"a\" id=\"n2\"></td>\r\n");
      out.write("			<td class=\"a\" id=\"n3\"></td>\r\n");
      out.write("			<td class=\"a\" id=\"n4\"></td>\r\n");
      out.write("			<td class=\"a\" id=\"n5\"></td>\r\n");
      out.write("			<td class=\"a\" id=\"n6\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>참조</th>\r\n");
      out.write("			<td colspan=\"9\" style=\"height:150px;\" name=\"aref\" id=\"aref\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br><input type=\"hidden\" name=\"alevel\"/>\r\n");
      out.write("	<table border=\"1\" class=\"vac_user\" name=\"vac_user\" id=\"vac_user\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"260px;\" style=\"background-color: #E2F0D9\">제목</th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" id=\"vsubject\" name=\"vsubject\" style=\"width:95%;\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>	\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"260px;\" style=\"background-color: #E2F0D9\">잔여휴가</th>\r\n");
      out.write("			<td><input type=\"text\" placeholder=\"15\">일</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("		<h2>휴가신청</h2>\r\n");
      out.write("		<table border=\"1\" class=\"vac_start\" name=\"vac_start\" id=\"vac_start\"> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<th id=\"start_end\" width=\"260px;\" style=\"background-color: #E2F0D9\">휴가시작일</th>	\r\n");
      out.write("				<td><input type=\"date\" id=\"startdate\" name=\"startdate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th id=\"start_end\" width=\"260px;\" style=\"background-color: #E2F0D9\">휴가종료일</th>\r\n");
      out.write("				<td><input type=\"date\" id=\"enddate\" name=\"enddate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("			\r\n");
      out.write("	<h2 class=\"text\">사유</h2>\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"editor\" class=\"initial-size\"></div>	\r\n");
      out.write("	    <input type=\"hidden\" id=\"quill_html\" name=\"vmemo\">\r\n");
      out.write("	    <script>\r\n");
      out.write("			\r\n");
      out.write("	  		var quill = new Quill('#editor', {\r\n");
      out.write("	    	  // Quill 설정 옵션\r\n");
      out.write("	    	});\r\n");
      out.write("	\r\n");
      out.write("	    	// 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("	    	var editorContainer = document.querySelector('#editor');\r\n");
      out.write("	    	editorContainer.addEventListener('click', function() {\r\n");
      out.write("	    	  quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("	    	});\r\n");
      out.write("	    \r\n");
      out.write("	        var toolbarOptions = [\r\n");
      out.write("	            ['bold', 'italic', 'underline', 'strike'],\r\n");
      out.write("	            ['link', 'image'],\r\n");
      out.write("	            [{ 'list': 'ordered' }, { 'list': 'bullet' }],\r\n");
      out.write("	            [{ 'header': [1, 2] }]\r\n");
      out.write("	        ];\r\n");
      out.write("			\r\n");
      out.write("	        var quill = new Quill('#editor', {\r\n");
      out.write("	            modules: {\r\n");
      out.write("	                toolbar: toolbarOptions\r\n");
      out.write("	            },\r\n");
      out.write("	            theme: 'snow'\r\n");
      out.write("	        });\r\n");
      out.write("	        \r\n");
      out.write("	        function myFunction(){\r\n");
      out.write("	        \r\n");
      out.write("	        }\r\n");
      out.write("	        \r\n");
      out.write("    </script>\r\n");
      out.write("	\r\n");
      out.write("	<h2 class=\"text\">별첨</h2>\r\n");
      out.write("	<table border=\"1\" class=\"type\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"260px;\" style=\"background-color: #E2F0D9\">첨부파일</th>\r\n");
      out.write("			<td><input type=\"file\" id=\"vfile\" name=\"vfile\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<input type=\"button\" id=\"submit\" value=\"기안하기\" style=\"width:230px;\">\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
